### ISSUE TITLE
change keyboard layout

### ISSUE THREAD

**Issue by matzeeg3** [dbisu/pico-ducky#10]
hi there,
i try to use it and until now i liked it a lot.
but i have an issue. i have to setup a different keyboard layout.
hope someone can help i this case.
thanks a lot
kind regards
matze

**Comment by Neradoc** [comment]
I started a repository of keyboard layouts, which is now the preferred way of adding layouts.
This sits here: https://github.com/Neradoc/Circuitpython_Keyboard_Layouts

I am experimenting with an online automated generator (for windows layouts), if you want to try:
https://www.neradoc.me/layouts/

Or feel free to open an issue on the layout repo, or ask me on the Adafruit discord #help-with-circuitpython (no PM) - I've already seen a few people using pico-ducky ask the same question over there.

**Comment by lucas2kdk** [comment]
Anyone got a solution for a Danish keyboard?

**Comment by matzeeg3** [comment]
> I started a repository of keyboard layouts, which is now the preferred way of adding layouts.
> This sits here: https://github.com/Neradoc/Circuitpython_Keyboard_Layouts
> 
> I am experimenting with an online automated generator (for windows layouts), if you want to try:
> https://www.neradoc.me/layouts/
> 
> Or feel free to open an issue on the layout repo, or ask me on the Adafruit discord #help-with-circuitpython (no PM) - I've already seen a few people using pico-ducky ask the same question over there.

i tryed the online generator but it did not work

**Comment by Neradoc** [comment]
Oh yeah the page is easily defeated by browser security rules that stop it from downloading the layout file from kbdlayout.info. I completely forgot that. I could make a server-side version of the script on the page, but I have concerns with security. I should remove the link, sorry.

The idea is rather to make them myself with a python script I'm working on and add them to the layout repo as people request them. But first I want to have a good enough version of the generator, so I don't have to give a pass to all of the files later, especially if they have hand-made fixes. At least not too soon.

Right now, it doesn't handle dead/composite keys very well (having `write("ô")` type `^` then `o`).

It would be better to ask about layouts over there:
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts

Here is the danish version. @lucas2kdk 
[da-layout.zip](https://github.com/dbisu/pico-ducky/files/7091939/da-layout.zip)

You put the files into the board's CIRCUITPY or its lib directory.
You then need to modify the ducky code as follows with the correct language files.
Change this:
```py
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
from adafruit_hid.keycode import Keycode
```
to this (note the language part of the module names)
```py
from keyboard_layout_win_da import KeyboardLayout
from keycode_win_da import Keycode
```
And this:
```diff
layout = KeyboardLayoutUS(kbd)
```
to this:
```diff
layout = KeyboardLayout(kbd)
```

**Comment by NadSeries** [comment]
It will be great if you could provide an italian keyboard layout for the pico ducky

**Comment by magnificent3** [comment]
Does anyone have a Portuguese layout?

**Comment by dbisu** [comment]
I have pushed a branch, Kronos, as a test for German keyboard layout.
Also, I think based on the site http://kbdlayout.info/ it should be possible to create other keyboard layout/scan code support.

**Comment by Neradoc** [comment]
Yeah it is possible, and I fixed the page for the javascript error: https://www.neradoc.me/layouts/

You can try it locally [from that branch](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/tree/layout-generator), though you'll need to know your way around python and shell scripts a little. Look at tests/make_validated.sh for usage. I should merge all that in the layout repository as well as a bunch of keyboard layouts that I made with it as they were requested and tested (at least a bit) by users.

Pico ducky could use a trick like this to avoid having to change the code when changing keyboard, by only renaming the layout and keycode files to keyboard_layout_ducky and keycode_ducky (not changing the extension).
```py
try:
    from keyboard_layout_ducky import KeyboardLayout
except ImportError:
    from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS as KeyboardLayout
# Keycodes
    from keycode_ducky import Keycode
except ImportError:
    from adafruit_hid.keycode import Keycode
```
And change `layout = ...` with that line:
```py
layout = KeyboardLayout(kbd)
```

**Comment by NadSeries** [comment]
Ok great!! Thanks a lot it was painful trying to map all the US character over an italian keyboard(and sometimes certain characters like { } wasn't available or rather they could not be injected). I used http://kbdlayout.info/ and  https://www.neradoc.me/layouts/, it works just fine for me.

**Comment by dbisu** [comment]
I've updated the code in the kronos branch to offer more generic import of new keyboard layouts from Neradoc/Circuitpython_Keyboard_Layouts
I also added keyboard-layouts.md with instructions on how to add non-US keyboard layouts.
I would appreciate it if someone with a non-US keyboard could try this out to validate the instructions.

**Comment by Timovl** [comment]
Is there an azerty layout? And how do I implement this in the code.py file?

**Comment by GamehunterKaan** [comment]
@Timovl > Is there an azerty layout? And how do I implement this in the code.py file?

Take A Look At These 2 Pages.
`https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/main/PICODUCKY.md`
 `https://www.neradoc.me/layouts/`

**Comment by NiklasRichter2222** [comment]
i do have a problem with the German keyboard i tried both methodes and nothing worked[
![Screenshot 2021-09-22 191108](https://user-images.githubusercontent.com/88104798/134390186-f3028be0-e62e-4f7d-84c5-681b5fdf5d9c.png)
![Screenshot 2021-09-22 191129](https://user-images.githubusercontent.com/88104798/134390188-6ee002dc-874b-4bd7-9ebb-117fec25125d.png)
](url)

**Comment by NiklasRichter2222** [comment]
and is there any way to implement üöä for me

**Comment by GamehunterKaan** [comment]
@NiklasRichter2222 This Is The Correct Code.py for German Keyboard.
```import usb_hid
from adafruit_hid.keyboard import Keyboard
from keyboard_layout_win_gr import KeyboardLayout
from keycode_win_gr import Keycode
import time
import digitalio
from board import *

duckyCommands = ["WINDOWS", "GUI", "APP", "MENU", "SHIFT", "ALT", "CONTROL", "CTRL", "DOWNARROW", "DOWN",
"LEFTARROW", "LEFT", "RIGHTARROW", "RIGHT", "UPARROW", "UP", "BREAK", "PAUSE", "CAPSLOCK", "DELETE", "END",
"ESC", "ESCAPE", "HOME", "INSERT", "NUMLOCK", "PAGEUP", "PAGEDOWN", "PRINTSCREEN", "SCROLLLOCK", "SPACE",
"TAB", "ENTER", " a", " b", " c", " d", " e", " f", " g", " h", " i", " j", " k", " l", " m", " n", " o", " p", " q", " r", " s", " t",
" u", " v", " w", " x", " y", " z", " A", " B", " C", " D", " E", " F", " G", " H", " I", " J", " K", " L", " M", " N", " O", " P",
" Q", " R", " S", " T", " U", " V", " W", " X", " Y", " Z", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"]

keycodeCommands = [Keycode.WINDOWS, Keycode.GUI, Keycode.APPLICATION, Keycode.APPLICATION, Keycode.SHIFT, Keycode.ALT, Keycode.CONTROL,
Keycode.CONTROL, Keycode.DOWN_ARROW, Keycode.DOWN_ARROW ,Keycode.LEFT_ARROW, Keycode.LEFT_ARROW, Keycode.RIGHT_ARROW, Keycode.RIGHT_ARROW,
Keycode.UP_ARROW, Keycode.UP_ARROW, Keycode.PAUSE, Keycode.PAUSE, Keycode.CAPS_LOCK, Keycode.DELETE, Keycode.END, Keycode.ESCAPE,
Keycode.ESCAPE, Keycode.HOME, Keycode.INSERT, Keycode.KEYPAD_NUMLOCK, Keycode.PAGE_UP, Keycode.PAGE_DOWN, Keycode.PRINT_SCREEN,
Keycode.SCROLL_LOCK, Keycode.SPACE, Keycode.TAB, Keycode.ENTER, Keycode.A, Keycode.B, Keycode.C, Keycode.D, Keycode.E, Keycode.F, Keycode.G,
Keycode.H, Keycode.I, Keycode.J, Keycode.K, Keycode.L, Keycode.M, Keycode.N, Keycode.O, Keycode.P, Keycode.Q, Keycode.R, Keycode.S, Keycode.T,
Keycode.U, Keycode.V, Keycode.W, Keycode.X, Keycode.Y, Keycode.Z, Keycode.A, Keycode.B, Keycode.C, Keycode.D, Keycode.E, Keycode.F,
Keycode.G, Keycode.H, Keycode.I, Keycode.J, Keycode.K, Keycode.L, Keycode.M, Keycode.N, Keycode.O, Keycode.P,
Keycode.Q, Keycode.R, Keycode.S, Keycode.T, Keycode.U, Keycode.V, Keycode.W, Keycode.X, Keycode.Y, Keycode.Z,
Keycode.F1, Keycode.F2, Keycode.F3, Keycode.F4, Keycode.F5, Keycode.F6, Keycode.F7, Keycode.F8, Keycode.F9,
Keycode.F10, Keycode.F11, Keycode.F12]

def convertLine(line):
    newline = []
    print(line)
    for j in range(len(keycodeCommands)):
		    if line.find(duckyCommands[j]) != -1:
		    	newline.append(keycodeCommands[j])
    print(newline)
    return newline

def runScriptLine(line):
    for k in line:
        kbd.press(k)
    kbd.release_all()

def sendString(line):
    layout.write(line)

def parseLine(line):
    if(line[0:3] == "REM"):
        # ignore ducky script comments
        pass
    elif(line[0:5] == "DELAY"):
        time.sleep(float(line[6:])/1000)
    elif(line[0:6] == "STRING"):
        sendString(line[7:])
    elif(line[0:13] == "DEFAULT_DELAY"):
        defaultDelay = int(line[14:]) * 10
    elif(line[0:12] == "DEFAULTDELAY"):
        defaultDelay = int(line[13:]) * 10
    else:
        newScriptLine = convertLine(line)
        runScriptLine(newScriptLine)

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayout(kbd)

# sleep at the start to allow the device to be recognized by the host computer
time.sleep(.5)

# check GP0 for setup mode
# see setup mode for instructions
progStatus = False
progStatusPin = digitalio.DigitalInOut(GP0)
progStatusPin.switch_to_input(pull=digitalio.Pull.UP)
progStatus = not progStatusPin.value
defaultDelay = 0
if(progStatus == False):
    # not in setup mode, inject the payload
    duckyScriptPath = "payload.dd"
    f = open(duckyScriptPath,"r",encoding='utf-8')
    print("Running payload.dd")
    previousLine = ""
    duckyScript = f.readlines()
    for line in duckyScript:
        line = line.rstrip()
        if(line[0:6] == "REPEAT"):
            for i in range(int(line[7:])):
                #repeat the last command
                parseLine(previousLine)
                time.sleep(float(defaultDelay)/1000)
        else:
            parseLine(line)
            previousLine = line
        time.sleep(float(defaultDelay)/1000)

    print("Done")
else:
    print("Update your payload")
```

**Comment by Neradoc** [comment]
> i do have a problem with the German keyboard i tried both methodes and nothing worked[

You installed the language modules inside another module (adafruit_hid), they go in the `lib/` directory.
[Maybe these instructions are clearer ?](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/main/PICODUCKY.md) I don't pretend to be good at writing guides, but there's a screenshot... 🤷

**Comment by NiklasRichter2222** [comment]
Thanks it worked

**Comment by DeDragonCZ** [comment]
Any way to do Czech keyboard..?

**Comment by NiklasRichter2222** [comment]
You go to this Website and do what thay say there
https://www.neradoc.me/layouts/

**Comment by NiklasRichter2222** [comment]
You download the .py files(the Big Button bot one of the two small ones and put all the diles exept the example Code in to the lib Folder

**Comment by NiklasRichter2222** [comment]
import usb_hid
from adafruit_hid.keyboard import Keyboard
from keyboard_layout_win_cz import KeyboardLayout
from keycode_win_cz import Keycode
import time
import digitalio
from board import *

duckyCommands = ["WINDOWS", "GUI", "APP", "MENU", "SHIFT", "ALT", "CONTROL", "CTRL", "DOWNARROW", "DOWN",
"LEFTARROW", "LEFT", "RIGHTARROW", "RIGHT", "UPARROW", "UP", "BREAK", "PAUSE", "CAPSLOCK", "DELETE", "END",
"ESC", "ESCAPE", "HOME", "INSERT", "NUMLOCK", "PAGEUP", "PAGEDOWN", "PRINTSCREEN", "SCROLLLOCK", "SPACE",
"TAB", "ENTER", " a", " b", " c", " d", " e", " f", " g", " h", " i", " j", " k", " l", " m", " n", " o", " p", " q", " r", " s", " t",
" u", " v", " w", " x", " y", " z", " A", " B", " C", " D", " E", " F", " G", " H", " I", " J", " K", " L", " M", " N", " O", " P",
" Q", " R", " S", " T", " U", " V", " W", " X", " Y", " Z", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"]

keycodeCommands = [Keycode.WINDOWS, Keycode.GUI, Keycode.APPLICATION, Keycode.APPLICATION, Keycode.SHIFT, Keycode.ALT, Keycode.CONTROL,
Keycode.CONTROL, Keycode.DOWN_ARROW, Keycode.DOWN_ARROW ,Keycode.LEFT_ARROW, Keycode.LEFT_ARROW, Keycode.RIGHT_ARROW, Keycode.RIGHT_ARROW,
Keycode.UP_ARROW, Keycode.UP_ARROW, Keycode.PAUSE, Keycode.PAUSE, Keycode.CAPS_LOCK, Keycode.DELETE, Keycode.END, Keycode.ESCAPE,
Keycode.ESCAPE, Keycode.HOME, Keycode.INSERT, Keycode.KEYPAD_NUMLOCK, Keycode.PAGE_UP, Keycode.PAGE_DOWN, Keycode.PRINT_SCREEN,
Keycode.SCROLL_LOCK, Keycode.SPACE, Keycode.TAB, Keycode.ENTER, Keycode.A, Keycode.B, Keycode.C, Keycode.D, Keycode.E, Keycode.F, Keycode.G,
Keycode.H, Keycode.I, Keycode.J, Keycode.K, Keycode.L, Keycode.M, Keycode.N, Keycode.O, Keycode.P, Keycode.Q, Keycode.R, Keycode.S, Keycode.T,
Keycode.U, Keycode.V, Keycode.W, Keycode.X, Keycode.Y, Keycode.Z, Keycode.A, Keycode.B, Keycode.C, Keycode.D, Keycode.E, Keycode.F,
Keycode.G, Keycode.H, Keycode.I, Keycode.J, Keycode.K, Keycode.L, Keycode.M, Keycode.N, Keycode.O, Keycode.P,
Keycode.Q, Keycode.R, Keycode.S, Keycode.T, Keycode.U, Keycode.V, Keycode.W, Keycode.X, Keycode.Y, Keycode.Z,
Keycode.F1, Keycode.F2, Keycode.F3, Keycode.F4, Keycode.F5, Keycode.F6, Keycode.F7, Keycode.F8, Keycode.F9,
Keycode.F10, Keycode.F11, Keycode.F12]

def convertLine(line):
    newline = []
    print(line)
    for j in range(len(keycodeCommands)):
		    if line.find(duckyCommands[j]) != -1:
		    	newline.append(keycodeCommands[j])
    print(newline)
    return newline

def runScriptLine(line):
    for k in line:
        kbd.press(k)
    kbd.release_all()

def sendString(line):
    layout.write(line)

def parseLine(line):
    if(line[0:3] == "REM"):
        # ignore ducky script comments
        pass
    elif(line[0:5] == "DELAY"):
        time.sleep(float(line[6:])/1000)
    elif(line[0:6] == "STRING"):
        sendString(line[7:])
    elif(line[0:13] == "DEFAULT_DELAY"):
        defaultDelay = int(line[14:]) * 10
    elif(line[0:12] == "DEFAULTDELAY"):
        defaultDelay = int(line[13:]) * 10
    else:
        newScriptLine = convertLine(line)
        runScriptLine(newScriptLine)

kbd = Keyboard(usb_hid.devices)
layout = KeyboardLayout(kbd)

# sleep at the start to allow the device to be recognized by the host computer
time.sleep(.5)

# check GP0 for setup mode
# see setup mode for instructions
progStatus = False
progStatusPin = digitalio.DigitalInOut(GP0)
progStatusPin.switch_to_input(pull=digitalio.Pull.UP)
progStatus = not progStatusPin.value
defaultDelay = 0
if(progStatus == False):
    # not in setup mode, inject the payload
    duckyScriptPath = "payload.dd"
    f = open(duckyScriptPath,"r",encoding='utf-8')
    print("Running payload.dd")
    previousLine = ""
    duckyScript = f.readlines()
    for line in duckyScript:
        line = line.rstrip()
        if(line[0:6] == "REPEAT"):
            for i in range(int(line[7:])):
                #repeat the last command
                parseLine(previousLine)
                time.sleep(float(defaultDelay)/1000)
        else:
            parseLine(line)
            previousLine = line
        time.sleep(float(defaultDelay)/1000)

    print("Done")
else:
    print("Update your payload")

**Comment by DeDragonCZ** [comment]
Hey, thanks for the help!

**Comment by dbisu** [comment]
I've created a branch, keyboard-layouts, to help make including the Neradoc keyboard layouts easier.
https://github.com/dbisu/pico-ducky/tree/keyboard-layouts
Let me know if this helps and I'll create a PR to include these changes.

**Comment by ivms-420** [comment]
any way to do spanish keyboard? :(

**Comment by dbisu** [comment]
ES is the locale code for Spanish.
https://github.com/dbisu/pico-ducky/releases/download/v1.2/pico-ducky-v1.2_win_es.zip

**Comment by ivms-420** [comment]
thank u so much this helped me a lot

**Comment by ivoiot** [comment]
ii'm having a problem with italian layout setting on my raspberry pi pico. when i execute some scrit with the simbol '{' or '}' it get stucked. any suggestion to fix it?
