### ISSUE TITLE
New button on USB Rubber Ducky v2.0

### ISSUE THREAD

**Issue by p-i-c-o** [dbisu/pico-ducky#103]
With the new rubber ducky rendition, a button was added, can we make this possible with the Pico Ducky code?
Heres an example from the Rubber Ducky Payload repo:

```
REM WAIT_FOR_BUTTON_PRESS halts payload execution until a button press is detected.
REM When this command is reached in the payload, no further execution will occur. The button definition (either set using BUTTON_DEF or the arming-mode default) will be suppressed.

STRING Press the button...
WAIT_FOR_BUTTON_PRESS
STRING The button was pressed!

REM The text "The button was pressed!" will not be typed until the button is pressed.
```

[REPOSITORY](https://github.com/hak5/usbrubberducky-payloads/tree/master/payloads/examples/Button)

**Comment by p-i-c-o** [comment]
Can anybody help me with this?

**Comment by dbisu** [comment]
This is syntax from DuckyScript 3.0.  I haven't started including those updates yet.  I'll mark this issue as a feature request to support things from 3.0.
