### ISSUE TITLE
Was working on wednesday not working now

### ISSUE THREAD

**Issue by iescobar76** [dbisu/pico-ducky#108]
Hello guys hope someone can enlighten me.  I have used this SW since it originally came out 2 years ago.  I used it on wednesday to show to my high school students how to make their own USB rubber ducky's. It worked fine on wednesday.  Today i showed them on a follow the teacher step by step and i used both payload studio and ducktoolkit to encode a simple hello world on my mac, just like two days ago.  Well the modified raspberry pi pico does not run the payload.dd (got the inject.bin renamed as usual) and nothing.  Checked again, checked again.  Nothing.  Used the payload.dd i created same way last wednesday and it works.  Used payloads i created 1 year ago and it works.  Use the generated inject.bin on a USB rubber ducky and it works.  

Any ideas?
cheers
ivan

**Comment by dbisu** [comment]
If possible, please include information from the debug serial port.
Another option could be go through the instructions in RESET.md.

**Comment by dbisu** [comment]
@iescobar76 Any more information on this issue?

**Comment by iescobar76** [comment]
Got it fixed sorry for the bother I had a virus creeping out my pc that’s why it was failing
Cheers ivan

Sent from my iPhone

On Oct 31, 2022, at 6:19 PM, Dave ***@***.***> wrote:

﻿

@iescobar76<https://github.com/iescobar76> Any more information on this issue?

**Comment by dbisu** [comment]
No bother, just trying to clean up old issues.
