### ISSUE TITLE
Pico Not Working

### ISSUE THREAD

**Issue by lucasB69** [dbisu/pico-ducky#109]
i have followed the instructions but its not working for some reason please help!

![Screenshot 2022-10-29 150142](https://user-images.githubusercontent.com/97230503/198848533-de5f832a-fb47-4d5b-af5d-c6ab8b040596.png)
![Screenshot 2022-10-29 150207](https://user-images.githubusercontent.com/97230503/198848535-5f1ad12d-ac66-49b2-91ca-46b1357f8f18.png)
![Screenshot 2022-10-29 150123](https://user-images.githubusercontent.com/97230503/198848539-bf1387ab-e69d-4cca-a6e5-b4f2145861b0.png)

**Comment by WarpOverload** [comment]
Same thing on my end, except I'm running Arch Linux. I tried bombing the flash and following the steps again, it didnt work. Maybe try using an older release?

**Comment by WarpOverload** [comment]
I tried using pico-ducky 1.3 and everything went smoothly. Try that and if it works, I guess you should just wait till the maintainers of this repository fix the issue.

**Comment by dbisu** [comment]
@lucasB69 Can you be more specific?  What isn't working?  If you bring up a serial terminal, are you getting any errors?

**Comment by lucasB69** [comment]
@dbisu thanks for responding but i fixed it!

**Comment by dbisu** [comment]
OK, great. Would you mind putting in a comment on how you fixed it as a closing comment?
Thanks.

**Comment by zigouris** [comment]
> @dbisu thanks for responding but i fixed it!

How did you fixed it cause i have exactly the same problem?

**Comment by qwertyuiop12lo** [comment]
same

**Comment by dbisu** [comment]
> same

Can you be more specific as to what is not working?

**Comment by dbisu** [comment]
Closing.  The original issue has been resolved.
