### ISSUE TITLE
Not an issue : possible hardware improvement ; RF picoducky

### ISSUE THREAD

**Issue by one-twoo** [dbisu/pico-ducky#111]
so i have salvaged these from an old wireless keyboard and mouse , the keyboard have an RF emitter @ 2.4 Ghz , and the reciver part is a little dongle working @ the same frequency and channel :
![r_2](https://user-images.githubusercontent.com/117367696/199736986-3f8f528b-27ef-4b63-ad10-99693b879028.jpg)
my idea is to connect the pico with the emitter part , and just plug the little dongle in the target system instead of plugging the bulcky pico 
![Sans titre](https://user-images.githubusercontent.com/117367696/199737934-b9819c06-46c4-48a5-ada5-117f7433bc4d.jpg)

advantages : more stealthy , and we can launch the payload from distance ( with the push button) 
the pico would be battery powered , the transmitter part connected with the usb port of the pico or GP pins ..., once the dongle is inserted in the target the pico should be immidiatly paired since the transmitter and reciever operates @ the same specific channel and frequency 
i dont know where to start or even if this is possible so im asking for a hint!

EDIT : since the picoducky pretend to be a regular keyboard is it possible to make it pretending to be a 'wireless' keyboard ?

**Comment by andreasbrett** [comment]
don't think that would work but definitely interesting idea to make a more stealthy ducky

**Comment by one-twoo** [comment]
> don't think that would work but definitely interesting idea to make a more stealthy ducky

hey andrea , ive seen alot of people transforming regular wired devices into wireless devices via bluetooth  modules , universal usb to wireless adapters and other RF emitters-reciever combo , im still convinced this is possible , at least the idea is good , unfortunately i dont have the necessary skills to do it , i hope someone think about it

**Comment by dbisu** [comment]
I think this is an interesting idea.  However, I see the idea as out of scope for the pico-ducky project.
In terms of wireless, support for the Pico W will be coming (hopefully) soon.

**Comment by one-twoo** [comment]
> I think this is an interesting idea. However, I see the idea as out of scope for the pico-ducky project. In terms of wireless, support for the Pico W will be coming (hopefully) soon.

thanks dbisu ! i hope you will be done soon with the new W

**Comment by one-twoo** [comment]
i didnt want to open a new issue for this , i ditched the old hardware and got the pico w , to my surprise after i flashed it with the latest release of circuitpython 8.0.0.beta4 i found that it had very little storage space : barely 490 kb 
is this normal , i had almost 1 mb with the regular pico , with that space i used to host 4 payloads plus all the assets needed to perform attacks without internet connection and exfiltrate data into the board , this could be a problem now ..
![20221108_221626](https://user-images.githubusercontent.com/117367696/200684074-1d849b6d-d17e-44de-b240-8b65236363a9.jpg)

**Comment by dbisu** [comment]
You'd have to ask in the adafruit discord about the size of the circuitpython releases.
The pico W has more functions with the wireless, so probably needs a larger image.

**Comment by dbisu** [comment]
Closing.  Pico W support is covered in a different issue/feature request.
