### ISSUE TITLE
Added all files, but no payload execution.

### ISSUE THREAD

**Issue by MadeinHeavan** [dbisu/pico-ducky#118]
Ive got the correct keyboard, and all files needed. I am running 7.0.0 adafruit and got the bundle 7. 

Any help would be appreciated.

**Comment by MadeinHeavan** [comment]
![image_2022-12-06_201239230](https://user-images.githubusercontent.com/117187902/206063258-20584221-a032-4683-a7d3-22980793ee1e.png)
![Screenshot 2022-12-06 201016](https://user-images.githubusercontent.com/117187902/206063267-bf7800ae-4353-418b-90ee-012d87ee6c8f.png)

**Comment by dbisu** [comment]
The first thing I see is that adafruit_tick should be a mpy file and not a folder.
You may want to download one of the release bundles to ensure all of your library dependencies are correct.

**Comment by MadeinHeavan** [comment]
thank you, I will try.

**Comment by MadeinHeavan** [comment]
it worked, thank you so much. btw I used a pre built release.

**Comment by dbisu** [comment]
Closing since it is working now.
