### ISSUE TITLE
Does not open as HID

### ISSUE THREAD

**Issue by soapy75** [dbisu/pico-ducky#119]
When i plug the pico in, it shows up as a normal drive and no exexution happens
![image](https://user-images.githubusercontent.com/68105703/206574741-c27f2641-5988-4760-8dcc-d758e1ac9c7d.png)
![image](https://user-images.githubusercontent.com/68105703/206574776-d5ec49c6-e1d9-4a13-a064-f9dbb7be6528.png)

**Comment by soapy75** [comment]
I tried replacing the payload but when i tried to delete the origional one it reappeard when i click back onto it.

**Comment by dbisu** [comment]
I would recommend starting with a release bundle and seeing if that gets it working.

**Comment by soapy75** [comment]
What's that? Is that the circuit python bundle?

**Comment by dbisu** [comment]
On of my release bundles for this project.  You can find the latest one here:
https://github.com/dbisu/pico-ducky/releases/tag/v1.4

**Comment by soapy75** [comment]
thanks

**Comment by soapy75** [comment]
I know im late, but i wiped it and tried again with the same results using the bundle download

**Comment by dbisu** [comment]
The only suggestion I have is to follow the instructions in RESET.md
https://github.com/dbisu/pico-ducky/blob/main/RESET.md
And then try to reload the bundle.
Once the file are written, make sure to eject the drive via Windows to make sure the files are flushed out to the device.

**Comment by soapy75** [comment]
ill try that now

**Comment by soapy75** [comment]
> The only suggestion I have is to follow the instructions in RESET.md https://github.com/dbisu/pico-ducky/blob/main/RESET.md And then try to reload the bundle. Once the file are written, make sure to eject the drive via Windows to make sure the files are flushed out to the device.

does it become an HID device as soon as i plug it in again, will it still show up as a flash drive?

**Comment by dbisu** [comment]
If you don't have any jumper wires connected, it will show up as both a USB HID as well as a USB Mass Storage device.

**Comment by soapy75** [comment]
![image](https://user-images.githubusercontent.com/68105703/210156167-80ad1ce4-84aa-4190-a79c-12b31430e96c.png)
Does this mean it is showing up as a HID? also, does the default payload do anything?

**Comment by dbisu** [comment]
On a Windows computer, the default payload should open notepad and type in Hello World!
Are you using a Pico or Pico W?

**Comment by soapy75** [comment]
normal pico

**Comment by soapy75** [comment]
Should i show the fles again since they look a little different?

**Comment by dbisu** [comment]
Do you have PuTTY installed to look at the debug output?

**Comment by soapy75** [comment]
Yes i have it installed but i have never used it for debugging
![image](https://user-images.githubusercontent.com/68105703/210156829-f0f61a0f-154c-4de6-b3e6-be39bacd71d0.png)

**Comment by dbisu** [comment]
In device manager, the Pico should show up under Ports as COM<something>, probably COM3
In PuTTY, select Serial and then enter the COM port
Once connected, hit Ctl-C and then Ctl-D, and post the results.

**Comment by soapy75** [comment]
![image](https://user-images.githubusercontent.com/68105703/210156916-1f6ab1f4-b8c4-4ae9-aae3-b9d0bf534f11.png)
?

**Comment by soapy75** [comment]
thats the closest thing to ports

**Comment by soapy75** [comment]
there are no other devices named COM or COM3

**Comment by dbisu** [comment]
That is weird. what happens if you unplug the Pico and reattach it to your computer?

**Comment by soapy75** [comment]
Nothing changed, could this be as i am using windows 8.1?

**Comment by dbisu** [comment]
No idea on that. I've only tried with Windows 10 or Ubuntu.

**Comment by soapy75** [comment]
mabye my file configuration?
![image](https://user-images.githubusercontent.com/68105703/210157061-9a61c618-7ab4-4cba-950a-75487f071a5d.png)
![image](https://user-images.githubusercontent.com/68105703/210157066-f780b23f-e3d4-4d67-b2d1-8d2a7af767a1.png)

**Comment by soapy75** [comment]
If not i might try using a flash drive or using someone elses windows 10 computer to see if thats the issue

**Comment by dbisu** [comment]
That looks correct.

**Comment by dbisu** [comment]
It could be the Windows version:
https://learn.adafruit.com/welcome-to-circuitpython/windows-7-and-8-1-drivers

**Comment by soapy75** [comment]
![image](https://user-images.githubusercontent.com/68105703/210157130-ab34d564-55be-4ee5-b6bc-5286a6762255.png)
very well could be  as windows wants me to update drivers too, i will do that and update you

**Comment by dbisu** [comment]
From the Adafruit page, RP2040 boards like the Pico are not supported by the Windows drivers, so you might need to use a Windows 10 or newer computer.

**Comment by soapy75** [comment]
oh, will the ducky scripts not even work on the computer? what about a flash drive?

**Comment by dbisu** [comment]
correct, I don't think the payloads will run properly because the computer isn't able to recognize the Pico as a HID.

**Comment by soapy75** [comment]
Ok thanks for the help, ill try and find another way to run ducky scripts

**Comment by soapy75** [comment]
Am i doing something wrong, i just found a windows 10 laptop and i tried it with the same resoults, am i supposed to change the files? In putty when i press open nothing happens. Ps sorry for bad image quality i took it using phone
![image](https://user-images.githubusercontent.com/68105703/210185539-1ee00c98-d97a-4344-b8aa-ba425039aa3f.png)

**Comment by dbisu** [comment]
In PuTTY, the Speed(Baud) needs to be set to 115200.

**Comment by soapy75** [comment]
Is there anything else that needs to be changed?

**Comment by soapy75** [comment]
Is there anything i can google to find the solution?

**Comment by dbisu** [comment]
In PuTTY, that is only thing that should be needed to be changed.
If you are on the latest firmware, the LED on the board should be blinking.

**Comment by Vivu5772** [comment]
![image](https://github.com/dbisu/pico-ducky/assets/105196858/4dfc07d0-bf0e-4856-adbb-9103000e756f)
in my case in control pannel it is showing as hid device then also it didn't run commads
