### ISSUE TITLE
what is a .dd file?

### ISSUE THREAD

**Issue by Apolycious** [dbisu/pico-ducky#12]
I have a few questions, one of them is what is a .dd file? and is there a way to use the Function button (e.g. F1 or F12)?

**Comment by Apolycious** [comment]
Is there any abbreviation for .did?

**Comment by thatITfox** [comment]
well it's just a made up name for the file extension, u can name it anything u want, and just change the settings in the python files, u can study more about files and how they work, i don't fully know what dd stands for tho, probably something for ducky, but don't know what the other d means, you can ask @dbisu for more information

**Comment by Apolycious** [comment]
Well thank you for the information, I'm kinda curious lol
