### ISSUE TITLE
Hi! Please help a noob.

### ISSUE THREAD

**Issue by 0067sdsm** [dbisu/pico-ducky#123]
So i tried to make it work lol, and i think everything is as it should but for some reason it doesnt work? I plug the pico in and it only shoes up as a mass storage device
(screen shot for reference:)
![Screenshot 2022-12-25 224141](https://user-images.githubusercontent.com/115708721/209483602-3c05c859-adb3-4fac-a50d-1113530425ef.png)

**Comment by alext30Developer** [comment]
Hi! I can see that you are missing the boot.py script, copy it over from the repository (step 9). Also verify that in the lib folder you got the following things: 
![explorer_McqiOzWi2v](https://user-images.githubusercontent.com/72646375/209875467-4a05f2b5-46d6-49fe-a2cf-ce2c7ffef7f4.png)
If you do, that's great! But if you don't, check out steps 5, 6, 7, 8.
The rest looks good. Let me know if that fixed it for you.

**Comment by 0067sdsm** [comment]
Thanks! Will do when I get home.

**Comment by alext30Developer** [comment]
Hi again! Did it work this time?

**Comment by 0067sdsm** [comment]
I'm in a completely different country XD I'm sorry, ill let you know tho

**Comment by 0067sdsm** [comment]
I'm pretty sure that in the lib I only had the adafruit_hid so that's probably it (+ the boot thingy) could you let me know where that stuff is just so when I get back I'd o t have to go looking through all the files and tutorials lol

**Comment by dbisu** [comment]
Look at the zip files here:
https://github.com/dbisu/pico-ducky/releases/tag/v1.4
Follow the instructions on this page and you should have a ready to go pico board.

**Comment by 0067sdsm** [comment]
Thanks :).

**Comment by 0067sdsm** [comment]
WORKS!!! this is so efing awsome thankyou!!!

**Comment by alext30Developer** [comment]
I'm glad it worked! Remember to close the issue btw
