### ISSUE TITLE
SENDHEX is not implemented

### ISSUE THREAD

**Issue by nclr** [dbisu/pico-ducky#128]
I'd like to output some raw hexadecimal data in order to control a ps3.
I see SENDHEX function is not implemented.

I've tried using usb_hid alone, but not successfully.

**Comment by dbisu** [comment]
I don't see SENDHEX in the ducky script manual.
If you need to send binary (hex) data, this is probably not the tool for you.  This tool acts like a USB keyboard.

**Comment by dbisu** [comment]
Closing, out of scope.
