### ISSUE TITLE
Direct control from a host pc

### ISSUE THREAD

**Issue by charredchar** [dbisu/pico-ducky#130]
Is it possible to allow direct control from a connected host PC, say over serial to the Pico, instead of relying on scripts saved to the Pico? I know this might be difficult for some keystrokes but the use case I am thinking of is working on a PC using my laptop when I don't have a spare keyboard or mouse available.

**Comment by dbisu** [comment]
No, I don't think this tool will meet that use case.

**Comment by dbisu** [comment]
Closing.  There are other solutions for working on a second computer.
