### ISSUE TITLE
it does not work nothing happens does the computer need python

### ISSUE THREAD

**Issue by h54t45tv45** [dbisu/pico-ducky#133]
**Describe the issue**
A clear and concise description of the symptoms

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by YashasSingh** [comment]
I honestly don't think it needs python script rather the adafruit-circuitpython-bundle-7.x-mpy-YYYYMMDD.zip is not the right one  to download  
use https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases?page=7
as this is the one that works


quick question do you guys know why this pico nuke is not working 

https://user-images.githubusercontent.com/121969113/216629868-f204881c-9eb8-46da-af64-de127f1c7b54.mp4

**Comment by dbisu** [comment]
The host or target computer does not need python. CircuitPython runs on the Pi Pico.

**Comment by beammedown** [comment]
@YashasSingh For me, the Nuke works after plugging the pico in while pressing the "BOOTSEL" Button.

So you probably have to press "BOOTSEL" and plug in the pico. After the pico appears, you should just be able to copy the nuke over and have it working. It should quickly disconnect and then reconnect.

**Comment by dbisu** [comment]
Were you trying to use CircuitPython 8.0.0?  If so, I have PR in process that updates support for 8.0.0

**Comment by dbisu** [comment]
If you are trying to use the flash_nuke image, please follow the instructions in RESET.md.
As beammedown noted, you need to be in the bootloader mode by holding the BOOTSEL button and having the Pico show up as RPI-RP2.

**Comment by dbisu** [comment]
Closing, support for CircuitPython 8.0.0 has been integrated into main.
