### ISSUE TITLE
Does not work with CircuitPython 8.0.0 on pico W

### ISSUE THREAD

**Issue by KeyPro77** [dbisu/pico-ducky#134]
Hello I just got my pico w and I followed the instructions(with the adafruit-circuitpython-bundle-8 and CircuitPython 8.0.0). I also couldnt find the previous version of CircuitPython. So I'm doing something wrong or is this repository not up to date?

Thanks for any reply!

**Comment by dbisu** [comment]
Make sure you are using the picow branch.  I have not yet merged pico w support into the main branch.  Now that CircuitPython 8.0.0 has been released, I'm hoping to get that done in the next few days.

**Comment by KeyPro77** [comment]
Thank you very much!
