### ISSUE TITLE
How do i access the web app

### ISSUE THREAD

**Issue by 1333481** [dbisu/pico-ducky#135]
I have a pico w and how do I access the web app? I have wifi set up in the settings.toml file.

**Comment by dbisu** [comment]
The Pico W as an AP defaults to 192.168.4.1
The web service runs on the standard port 80.
I'm working on updates to merge in the picow branch to main.  I'll make sure those instructions land in the README.

**Comment by 1333481** [comment]
> The Pico W as an AP defaults to 192.168.4.1 The web service runs on the standard port 80. I'm working on updates to merge in the picow branch to main. I'll make sure those instructions land in the README.

I am not able to access the IP it defaults to. I can access the CircuitPython web interface
