### ISSUE TITLE
Installed everything as told in the instructions, the web page doesn't load still

### ISSUE THREAD

**Issue by linuzzx** [dbisu/pico-ducky#138]
I followed the instructions, added a secrets.py with `secrets = {'ssid':'name','password':'pwd'}` still not working
PS: the led just blinks slowly

**Comment by dbisu** [comment]
Are you able to connect to the AP on the Pico W?
As the project is currently designed, the Pico W acts like an AP.  You would need to change the wifi connection code if you want it to connect to an existing AP.

**Comment by linuzzx** [comment]
oh didn't know that. well I don't see any wifi APs though

**Comment by dbisu** [comment]
Please include a dump from the debug serial to help look at what is going on.

**Comment by linuzzx** [comment]
How?

**Comment by dbisu** [comment]
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Comment by linuzzx** [comment]
Got it working, thanks

**Comment by dbisu** [comment]
If it is working now, please close this issue.
Thanks.

**Comment by dbisu** [comment]
Closing, resolved.
