### ISSUE TITLE
Other Keyboard Layouts don't seem to work anymore

### ISSUE THREAD

**Issue by linuzzx** [dbisu/pico-ducky#139]
I made a script in the web GUI with "STRING y". I did install the correct lang files and modified the code.py as instructed

Still the py outputted z (I use german layout)

**Comment by dbisu** [comment]
I think I may know the issue.  try commenting out lines 11 &12 in code.py and then making the correct changes for non-US keyboards in duckyinpython.py.

**Comment by linuzzx** [comment]
I did

**Comment by dbisu** [comment]
I think there is duplicated code.  all of the keyboard code should be in duckyinpython.py now.  keep everything commented out in code.py and make the changes in duckyinpython.py instead.

**Comment by linuzzx** [comment]
Yep that worked, I removed lines 7-17 and did the stuff in duckyinpython.py. works thanks
you should probably remove that in the repo too

**Comment by dbisu** [comment]
Yes, I'll make that change.  thanks for testing.
