### ISSUE TITLE
When I plug it in it only opens the file explorer.

### ISSUE THREAD

**Issue by Kyle2929** [dbisu/pico-ducky#147]
When I plug in the pico, It only opens the file explorer and does nothing else. The code.py is not a python file and goes to notepad.

![Screenshot 2023-02-28 193901](https://user-images.githubusercontent.com/126630204/222015371-afc1e2d7-f173-4c4b-8246-b45ae57f7583.png)

**Comment by leggiand** [comment]
you have to copy boot.py,duckyinpython.py, code.py, webapp.py, wsgiserver.py from the project to the root folder of the pico

**Comment by Kyle2929** [comment]
I was on an older release to see if it would work with it. I just put it back on the newest release and it still doesnt work.
![Screenshot 2023-03-01 160605](https://user-images.githubusercontent.com/126630204/222265286-11af8e21-2828-4dbc-8152-0ce4a021a04e.png)
![Screenshot 2023-03-01 160626](https://user-images.githubusercontent.com/126630204/222265302-21403ad9-2b70-4ae8-bbfa-6dc390fcb256.png)

**Comment by dbisu** [comment]
Please use PuTTY or Mu editor to get the debug serial logs. This will help determine the issue.

**Comment by dbisu** [comment]
Closing, no updates.
