### ISSUE TITLE
Cant connect to webservice

### ISSUE THREAD

**Issue by leggiand** [dbisu/pico-ducky#148]
when i go to 
192.168.4.1:60 for connect to the webservice it says connection timeout

connect the pico when the payload is loaded and go to 192.168.4.1:80

to connect to the webservice

![image](https://user-images.githubusercontent.com/114882821/222222936-e2a8cf8a-df83-407c-aea0-41bd5bf676cc.png)

i also tried with and without payload on

**Comment by dbisu** [comment]
verify that your computer connected to the Pico W access point using the ssid and password you put into secrets.py.

**Comment by leggiand** [comment]
i check it and they're right

**Comment by Th34rch1t3ctOfficial** [comment]
> i check it and they're right

And do you have device in the setup mode? Jumper between pin 1 (GP0) and pin 3 (GND). 

https://github.com/dbisu/pico-ducky#setup-mode

The pico-ducky doesn't run like the om.g plug, unfortunately. You must first run the device in the setup mode, then connect to the wifi AP you set in secrets.py, edit or create payload, unplug the jumper, and unplug it from the PC, then plug it to the PC again.
