### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by Astolfo-USBPico** [dbisu/pico-ducky#15]
So when i do all of the steps to make the pico a bad usb it works. But, then the next time i plug it into my computer it is labeled USB Drive (I:) and all there is boot_out.txt. So then i try to hold the white button while plugging it in and its now known as RPi1-RPI2 and then i download circuitpython again and paste it in and now it just disconnects and reconnects as USB Drive (I:) again and I cant find a way to fix it so if you can please help me.

**Comment by Astolfo-USBPico** [comment]
nvm i fixed it

**Comment by Anonymous101707** [comment]
How did you fix it?
