### ISSUE TITLE
pico-ducky not executing payload

### ISSUE THREAD

**Issue by Brewas** [dbisu/pico-ducky#152]
When I drop payload.dd file it does not run, nothing happens. Tried new versions, changing dd to txt, editing code.py. It still doesn't work. (I use raspberry pi pico W)

**Comment by dbisu** [comment]
The payload doesn't automatically run as soon as you drop the payload.dd file on to the device. you need to restart the device. It runs automatically on boot, or if you connect a button to GP22, it will run when you press the button.

**Comment by Brewas** [comment]
Thanks, but turns out that I was not following your tutorial on github correctly. I was copying wrong py files to my pico. Still thanks.
