### ISSUE TITLE
Wi-Fi section of bad usb

### ISSUE THREAD

**Issue by Ojamyjack** [dbisu/pico-ducky#154]
I follow all the steps listed to set up my pico but when I attempt to connect to the web server I just don’t get any sort of response Is there any extra steps that may not be listed. I do have the pico w.

**Comment by responsivereality** [comment]
Yep, I have the exact same problem. Would love to see a solution from the creator.

**Comment by dbisu** [comment]
Please post a dump of the debug serial from the device.

The steps to use the wifi:
Make sure secrets.py has the AP name and password you want to create (Pico W acts like an AP).
Connect to the AP from your attacking device.
Go to http://192.168.4.1
You should see the main webpage for the pico-ducky webserver.

**Comment by responsivereality** [comment]
Hey dbisu. Thanks for the prompt response. Unfortunately, my Raspberry Pi Pico W does not have any GPIO pins soldered, so I do not know how to get info from the debug serial. How do you setup "secrets.py"? There was nothing about that in the instruction page. Thanks for your helo.

**Comment by dbisu** [comment]
The debug serial is available via the USB port. Use PuTTY, minicom, or Mu editor to access the debug port.

**Comment by Ojamyjack** [comment]
> 

Where do I find secrets.py and set that file up

**Comment by responsivereality** [comment]
Mu is not giving me any data. I cannot access the serial information, all it does is open a REPL.

**Comment by dbisu** [comment]
> > 
> 
> Where do I find secrets.py and set that file up

I thought the README had that information.  I've updated README.md to include how to create secrets.py.

**Comment by responsivereality** [comment]
Thank you so much! It now works as intended, except for one minor thing: When I upload a payload onto it from the web interface such as this:

DELAY 2000
COMMAND SPACE
DELAY 1000
STRING https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
DELAY 1000
ENTER

It turns into this because of the special characters like slashes and question marks and colons:

DELAY 2000
COMMAND SPACE
DELAY 1000
STRING https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ%26ab_channel%3DRickAstley
DELAY 1000
ENTER

Is there any fix? This is a rickroll lol

**Comment by Ojamyjack** [comment]
It may just be me being stupid but I still couldn’t get it to work maybe I’m inputting data in the wrong place if anybody has an example of the secrets file or if there is a video of someone setting it up could someone give me that link

**Comment by responsivereality** [comment]
Sure, I'll send a short video

**Comment by Ojamyjack** [comment]
> Sure, I'll send a short video

Where too so I can see it

**Comment by responsivereality** [comment]
https://drive.google.com/file/d/1nJIvFESKK31g2-HW-2yvD0DOflEfLeOT/view?usp=drivesdk

It’s a 3 minute video so it’ll take a second to process

**Comment by Ojamyjack** [comment]
Thanks that works just gotta find out how to run commands I can write new ones but no button to run

**Comment by rickviper** [comment]
I have set up secrets.py by putting ssid and password of my wifi as instructed in the readme section but still my pico w is not connecting to my wifi. Can anyone help me?

**Comment by responsivereality** [comment]
The Pico W itself doesn't connect to WiFi. It creates a WiFi network that is by default called "BadAPName", that you then connect to, enter 192.168.4.1 on your browser, and execute payloads wirelessly.

**Comment by rickviper** [comment]
Thank u for helping out, it was me being stupid, didn't knew much about how it worked.
