### ISSUE TITLE
.uf2 Not Working

### ISSUE THREAD

**Issue by NonTrusted** [dbisu/pico-ducky#160]
When i copy .uf2 file to the Pi Pico, It does reconnect as "CIRCUITPY" but it doesn't have the files i need, it shows "boot_out.txt" only and there is:

Adafruit CircuitPython 8.0.4 on 2023-03-15; Raspberry Pi Pico with rp2040
Board ID:raspberry_pi_pico

Can anyone help????

**Comment by dbisu** [comment]
This has been seen before. I think it must be an issue in the CircuitPython loader.
Follow the instructions in [RESET.md](https://github.com/dbisu/pico-ducky/blob/main/RESET.md)

**Comment by NonTrusted** [comment]
> This has been seen before. I think it must be an issue in the CircuitPython loader. Follow the instructions in [RESET.md](https://github.com/dbisu/pico-ducky/blob/main/RESET.md)

THANKS SM BROOOOO, IT WORKEDDDDD, HAPPY ASS FCKK

**Comment by dbisu** [comment]
Closing, issue resolved.
