### ISSUE TITLE
pico-ducky gets no IP in AP mode

### ISSUE THREAD

**Issue by danielw1990** [dbisu/pico-ducky#161]
**Describe the issue**
Pico Pi W seems to  not get an IP when set up in AP mode.   
Prints out: "🐍Wi-Fi: No IP"

I can connect to the AP as expected, but trying to access 192.168.4.1 times out.

**To Reproduce**
1) Set up pico-ducky.   
2) Plug in and wait for the aforementioned message.
3) connect to AP
4) Try to access 192.168.4.1 and wait for timeout

**Expected behavior**
According to the guide it should have the IP 192.168.4.1 and should give a response if accessed via port 80 by a we bbrowser.

**Screenshots**

**Additional context**
Payload gets executed too, mode change via pins works. Everything else seems to work.

**Comment by danielw1990** [comment]
I tried to connect to the AP with my desktop PC. And somehow there I get a response.

So the problem changes to:
No response if accessed via chrome on Android and strange message printed out that claims to have no IP.

**Comment by responsivereality** [comment]
If you are still having trouble with this, I created an updated repository for the Raspberry Pi Pico W. It does not contain any changed code, I have merely reorganised the amazing code that Dbisu developed. https://github.com/responsivereality/Dbisu-Pico-W-Ducky

**Comment by dbisu** [comment]
It is possible that your phone won't stay connected to the Pico W because of the internet checks built into Android.
