### ISSUE TITLE
payload

### ISSUE THREAD

**Issue by AkumaBiNoTori** [dbisu/pico-ducky#162]
i did everything exactly but the payload wont work the pico ducky respond when i ground the pins mentioned and everything its even shown as a keyboard when i plug it but no matter what the payload wont work. i tried to download circuit python 8.0.0 as i was on 8.0.5 but same result

**Comment by responsivereality** [comment]
Hi there. Are you using the Pico W or the regular Pico? If you are using the W, the default state of the Mass Storage Device is switched.

**Comment by responsivereality** [comment]
> i did everything exactly but the payload wont work the pico ducky respond when i ground the pins mentioned and everything its even shown as a keyboard when i plug it but no matter what the payload wont work. i tried to download circuit python 8.0.0 as i was on 8.0.5 but same result

Hi there. Are you using the Pico W or the regular Pico? If you are using the W, the default state of the Mass Storage Device is switched.

**Comment by AkumaBiNoTori** [comment]
Its a regular pico

**Comment by MikeCVermeer** [comment]
Same issue here. Installed everything but the payload does not get executed. My pc sees the pico as a HID

**Comment by dbisu** [comment]
Which pins do you have tied together? If you have Pin 0 (GPIO 0) tied to Pin 3 (GND), the payload will not deploy automatically on boot, per design.

**Comment by AkumaBiNoTori** [comment]
Well i didnt tie any pins at first but then i tied gp4 and ground and the pin that hides the pico still no payload but the pico is hidden

**Comment by dbisu** [comment]
Are you on the latest code or one of the releases?

**Comment by AkumaBiNoTori** [comment]
Right now i am on 8.0.0 last time i was on 8.0.5 i get the same result in both

**Comment by dbisu** [comment]
With the current code in the repo, this is how the GPIO works for showing or hiding the Pico as a USB device
Pico:
*   GP15 not connected == USB visible
*   GP15 connected to GND == USB not visible

Pico W:
*   GP15 not connected == USB NOT visible
*   GP15 connected to GND == USB visible

**Comment by AkumaBiNoTori** [comment]
Yes when i connect it the usb becomes invisible but still the payload wont work

**Comment by dbisu** [comment]
Please get some debug logs
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Comment by AkumaBiNoTori** [comment]
i am having trouble using the PuTTY  software i connected it and i am running it from cmd idk which command to choose

**Comment by AkumaBiNoTori** [comment]
nvm i figured it out

**Comment by AkumaBiNoTori** [comment]
![Capture](https://user-images.githubusercontent.com/62224602/230759475-6e3e4aa4-7aa8-4748-9c78-e5bdbb7877db.PNG)
this is hwat i get when i use it it just stays like this

**Comment by dbisu** [comment]
In your PuTTY terminal, hit Ctl+c then Ctl+d to restart the program.

**Comment by AkumaBiNoTori** [comment]
okay here is my update 
![123](https://user-images.githubusercontent.com/62224602/231527169-44d09f6e-a791-4749-a3b9-cdf63f0bf626.PNG)

**Comment by dbisu** [comment]
The code cannot find the file payload.dd  That file needs to be in the root folder of your Pico.

**Comment by AkumaBiNoTori** [comment]
i do have it in the root 
![1](https://user-images.githubusercontent.com/62224602/231890940-c07fa4fc-6e4f-4b63-a7fe-48792ab63a7d.PNG)

**Comment by dbisu** [comment]
It appears you have file extensions hidden. Make sure the file is named payload.dd and not payload.dd.txt

**Comment by AkumaBiNoTori** [comment]
let me try

**Comment by AkumaBiNoTori** [comment]
![2](https://user-images.githubusercontent.com/62224602/231892238-0aea62de-3bb4-4ba1-a72a-c1cd7ebc2ab5.PNG)
it is .txt here but i cant change it

**Comment by dbisu** [comment]
Open File Explorer (This PC) → Click on View option in upper menu to view Ribbon menu → Check the box next the File name extensions option.
You should then get the full file name if you try to rename it.

**Comment by AkumaBiNoTori** [comment]
finally it worked
thanks so much for your help

**Comment by AkumaBiNoTori** [comment]
just a small question if i want it to inject certain packets i should place those packets normally in the root of the pico or will it cause any problem?

**Comment by dbisu** [comment]
Not sure what you mean by packets. This tool emulates a keyboard, not a network device.

**Comment by AkumaBiNoTori** [comment]
didnt mean a packet i meant a file malware like can i use it as a small usb that has data and i can transfer this data and make my code run it

**Comment by Plato13** [comment]
My payload is not working to. Anyone else can help me ?

**Comment by Plato13** [comment]
![20230415_024242.jpg](https://user-images.githubusercontent.com/130696202/232171191-8293d0da-0b54-4fe1-9c40-8391a66e09f5.jpg)

![20230415_024231.jpg](https://user-images.githubusercontent.com/130696202/232171190-90d159c1-8c67-4622-8fae-987356d861a1.jpg)

**Comment by dbisu** [comment]
> didnt mean a packet i meant a file malware like can i use it as a small usb that has data and i can transfer this data and make my code run it

Yes, there is around 1MB of space on the Pico.

**Comment by AkumaBiNoTori** [comment]
can i add an sd card module to it ? or will it cause problems?

**Comment by dbisu** [comment]
Pi Pico boards don't support sd cards directly. Adding sd card support to the pico is outside the scope of this project.

**Comment by AkumaBiNoTori** [comment]
okay thank you so much for your help
