### ISSUE TITLE
payload keyboards command doesn't match

### ISSUE THREAD

**Issue by clackes** [dbisu/pico-ducky#169]
the keyboard  and the key inserted by duckyinpython.py doesn't match, for example, it insert § instead of | 
can someone help me pls???

**Comment by dbisu** [comment]
Make sure you are using the correct layout for your keyboard. The code defaults to US keyboard layout.

**Comment by clackes** [comment]
How can I know what layout do I need to use??

**Comment by dbisu** [comment]
Please look at the Keyboard layouts section of the README.
[Keyboard layouts](https://github.com/dbisu/pico-ducky#changing-keyboard-layouts)

**Comment by clackes** [comment]
thank you
