### ISSUE TITLE
Rasberry pi pico w issue with the payload runing

### ISSUE THREAD

**Issue by Crazzzzyyyy223** [dbisu/pico-ducky#179]
Im having some issue getting the payloads to run on my raspberry Pico w i copy all the stuff in the places and put secrets.py in the root and put a payload.dd with a payload and nothing happens at all and then when i unplug it it doesn't show back up and then i have to reset my Pico.

**Comment by dbisu** [comment]
Please post data from the debug serial port.
As for the device not showing up, by default with this code, the Pico W will not enumerate as a USB drive without being in USB mode.
[USB Mode](https://github.com/dbisu/pico-ducky#usb-enabledisable-mode)

**Comment by Crazzzzyyyy223** [comment]
how do i check the debug cereal port

**Comment by dbisu** [comment]
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Comment by Crazzzzyyyy223** [comment]
![Screenshot 2023-05-16 193728](https://github.com/dbisu/pico-ducky/assets/133737884/f167a4dd-96cd-4e4e-9729-2a8affb796df)
my port is empty and the payload is still not working

**Comment by Crazzzzyyyy223** [comment]
NVM I GOT I TO WORK JUST HAD TO AUTO  RELOAD

**Comment by Crazzzzyyyy223** [comment]
THANK YOU SO MUCH
