### ISSUE TITLE
Typing speed of the Pico

### ISSUE THREAD

**Issue by Timbolimbo** [dbisu/pico-ducky#183]
I am currently using the Raspberry Pi Pico with this pico-ducky script. My question is if it is possible to make the pico type faster than its current speed because I think it is sort of slow.

**Comment by dbisu** [comment]
I believe the limitation is in the HID driver of CircuitPython.

**Comment by Timbolimbo** [comment]
Okay, but when I try to open the HID driver in VS Code it only makes scribbly letters and I don't know how to change that.

**Comment by dbisu** [comment]
You would need to look at the adafruit-hid repo [here](https://github.com/adafruit/Adafruit_CircuitPython_HID).

**Comment by dbisu** [comment]
Closing, typing speed is out of scope for this project. Check with the adafruit-hid library.
