### ISSUE TITLE
Feature request not BuG

### ISSUE THREAD

**Issue by Kronos2308** [dbisu/pico-ducky#200]
## In any case, I wanted to leave the public code in case someone is interested or wants to do something with it.

Saludos

### [https://github.com/Kronos2308/pico-ducky](https://github.com/Kronos2308/pico-ducky)
![RP2040 Zero Wiring](https://github.com/Kronos2308/pico-ducky/blob/main/images/IMG_20230801_062556e.jpg?raw=true)

**Comment by Kronos2308** [comment]
![IMG_20230817_020155](https://github.com/dbisu/pico-ducky/assets/36446521/65e33563-22f0-4caf-b7fe-bd275b93fbc4)

**Comment by dbisu** [comment]
That is a neat little board.

**Comment by Kronos2308** [comment]
Works like this
![ONE](https://github.com/dbisu/pico-ducky/assets/36446521/a42d18a1-bdf2-445e-8357-6b6c056d2d21)
also i fix the code to be hable to chsnge paylodas usig a power bank

**Comment by dbisu** [comment]
Closing as completed.
Thanks for sharing this project.
