### ISSUE TITLE
.uf2 not working

### ISSUE THREAD

**Issue by BlakeBergstrom** [dbisu/pico-ducky#201]
when I uploaded the correct .uf2 file my pico never showed up as "CIRCUITPY". I tried unplugging and plugging it back into my computer but it no longer appears in my computer at all.

**Comment by dbisu** [comment]
If you are using a Pico W, after loading boot.py, by default the USB mass storage device will be hidden. See the section in README.md about USB show/hide.

**Comment by BlakeBergstrom** [comment]
Ok thanks.

**Comment by dbisu** [comment]
Closing resolved
