### ISSUE TITLE
cant copy the .UF2 file 

### ISSUE THREAD

**Issue by redshift-cyber** [dbisu/pico-ducky#203]
**Describe the issue**
So i did all the steps before and it worked. Then the next day i deleted all the files off the pi and wanted to do the same thing as before. This time however the pico is alr named as "CIRCUITPY" and whenever i copy the .UF2 file i get an error saying there isnt enough storage space.

**To Reproduce**
Copy the .UF2 file to the alr named circuitpy it gives an error saying "Not enough storage space"

**Expected behavior**
I expected the .uf2 file to get copied there where the pi would reboot.

**Screenshots**
![image](https://github.com/dbisu/pico-ducky/assets/79589166/cb56e952-698d-4e85-a30c-7042be71d5fb)

**Comment by dbisu** [comment]
If you want to update the uf2 version, you need to hold the reset button on boot of the Pico. You should then see the Pico show up as RPI-RP2.
You can then copy the new uf2 file.

**Comment by dbisu** [comment]
Closing, resolved
