### ISSUE TITLE
After doing all that setup raspberry pi pico doesn't recognize as hid device and not run commands simply open as storage device.

### ISSUE THREAD

**Issue by Vivu5772** [dbisu/pico-ducky#211]
**Describe the issue**
A clear and concise description of the symptoms

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug info**
If possible, include debug serial data.
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Additional context**

**Comment by Vaneer420** [comment]
also experiencing this issue

**Comment by dbisu** [comment]
Please see [USB Enable/Disable](https://github.com/dbisu/pico-ducky#usb-enabledisable-mode) section.
By default, a Pico W will not show up as a USB mass storage device to enable the web service to use the storage.

**Comment by tranquillechat** [comment]
Hello,
Same wird issue, follow the quickstart version 2.0 and 1.4, or the complete guide, everything copy fine, but i have no "hello world" payload working, deconnect/reconnect, nothing.

Any ideas of any mistapes ?!

**Comment by dbisu** [comment]
Closing.
