### ISSUE TITLE
I can't change my keyboard layout, what am I doing wrong

### ISSUE THREAD

**Issue by wsrb77** [dbisu/pico-ducky#218]
I went by instructions but he still uses the us layout.
Pictures are attached

ADD the de-Layout
<img width="727" alt="Screenshot 2023-12-07 112232" src="https://github.com/dbisu/pico-ducky/assets/153182380/27c4283b-82d8-47e3-ada8-0382b2a6c557">

Change Layout 
<img width="624" alt="Screenshot 2023-12-07 112514" src="https://github.com/dbisu/pico-ducky/assets/153182380/09b9246d-c8a8-4cd1-b8f2-9e2680432958">

**Comment by dbisu** [comment]
Looks correct. what errors are you getting?

**Comment by wsrb77** [comment]
I didn't have any errors, everything worked fine, except that it used the US keyboard layout again when executing the payload.
I found the preconfigured file in German, and it worked regardless. Thank you anyway.

**Comment by dbisu** [comment]
Closing as resolved.

**Comment by exequze** [comment]
i had the same issue, you have to add "adafruit_hid." to the keayboard layout for other languages for it to work. maybe add this to the code :)
