### ISSUE TITLE
Issue booting payload

### ISSUE THREAD

**Issue by SkylerDuggan** [dbisu/pico-ducky#22]
I've got the lib, the code.py, and the payload setup however nothing happens.
Please help.

**Comment by dbisu** [comment]
Which version of the uf2 file did you try to install?  Version 7.0.0 was just released yesterday.  You would need to make sure you are downloading the 7.x lib files.  I haven't done any testing with 7.0.0 yet and have not updated the documentation to point at 7.x libs.
