### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by smrf356** [dbisu/pico-ducky#220]
when I plug the usb in to my chrome book and my pc it comes up as a usb device but it dose not play my payload. 
I redownloaded the Pico ducky software 3 or 4 times but it dose not work

**Comment by dbisu** [comment]
Are you using a Pico or Pico-W?
Please include debug serial data.
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)
On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Comment by smrf356** [comment]
I am sorry I don't want to waste your time but I have know idea how to use puddy I just got into it 5 days ago
(I am using just a Pico not a Pico-w)

**Comment by dbisu** [comment]
Have you tried using one of the preconfigured release bundles?
You can find them [here](https://github.com/dbisu/pico-ducky/releases)
They tend to work best for new users.

**Comment by smrf356** [comment]
![Screenshot (14)](https://github.com/dbisu/pico-ducky/assets/151853654/c239e48f-cda0-4d5e-adfc-fc54400c3ea7)
![Screenshot (16)](https://github.com/dbisu/pico-ducky/assets/151853654/2be81f43-b1c2-4a3e-a600-2958fef6f1f3)
I followed it and it still did not work is this what it is supposed to look like?

**Comment by dbisu** [comment]
You are missing most of the recent files. What release version did you use? Version 2.0 is the latest and currently supported version.
https://github.com/dbisu/pico-ducky/releases/tag/v2.0

**Comment by smrf356** [comment]
can you show me a pic of what it is meant to look like

**Comment by dbisu** [comment]
You should have 6 .py files in the root of the Pico.
Make sure you are following the instructions in INSTALL.txt or in the INSTALL section at https://github.com/dbisu/pico-ducky/releases/tag/v2.0
This should walk you through how to get it working.

**Comment by smrf356** [comment]
![Screenshot (17)](https://github.com/dbisu/pico-ducky/assets/151853654/e0452ed3-0f40-48b1-95b6-4b9aab61cde9)
like this?

**Comment by smrf356** [comment]
i got it to work
thank you so much for the help sorry I am kind of dumb

**Comment by dbisu** [comment]
Good deal.
Hope you learned a bit about using the Pico.

Closing as resolved.
