### ISSUE TITLE
stupid question

### ISSUE THREAD

**Issue by FrazeDev** [dbisu/pico-ducky#223]
Hello, as the title says its a stupid can someone tell me if these are the right jumpers for rasbery ? 
https://www.anodas.lt/jungiamieji-laidai-kaistis-kaistis-justpi-65-vnt?utm_source=kaina24.lt&utm_medium=referral

if not can someone give me a link to them

**Comment by Ixian1313** [comment]
Stop. Unsubscribe

**Comment by dbisu** [comment]
Those could work. Really all you need is a short piece of wire to connect the pins together.

**Comment by dbisu** [comment]
Closing, answered.
