### ISSUE TITLE
Please tell me that the arrow keys at least work

### ISSUE THREAD

**Issue by ShadowFlareon** [dbisu/pico-ducky#227]
Do the arrow keys work

**Comment by ShadowFlareon** [comment]
and does TAB work

**Comment by dbisu** [comment]
Yes, all of those keys work. Please look [here](https://github.com/dbisu/pico-ducky/blob/main/duckyinpython.py#L26) for the supported key commands.

**Comment by dbisu** [comment]
closing, answered.
