### ISSUE TITLE
ducky script isn't running

### ISSUE THREAD

**Issue by devraaj11** [dbisu/pico-ducky#235]
**Describe the issue**
the ducky script isn't running when connecting the pico
it just shows up as a usb device
all files were copied according to the install guide

**Expected behavior**
payload.dd is supposed to open notepad

**Screenshots**
Files in pico

![picofile](https://github.com/dbisu/pico-ducky/assets/160491512/b4c26823-89de-419f-b2b1-8a961292fd70)
files in lib

![libfile](https://github.com/dbisu/pico-ducky/assets/160491512/1471fa1b-44e7-4dc2-8706-52a9c9d9a8d9)

payload file

![payload](https://github.com/dbisu/pico-ducky/assets/160491512/491fb894-48d2-4947-aee4-e75d28952fe0)

**Comment by dbisu** [comment]
A couple of questions. Which keyboard layout are you using? Do you have setup mode still enabled? the scripts only run on boot, so make sure you update your script, then unplug and replug your pico.

**Comment by devraaj11** [comment]
> A couple of questions. Which keyboard layout are you using? Do you have setup mode still enabled? the scripts only run on boot, so make sure you update your script, then unplug and replug your pico.

keyboard is eng-us
step mode is off
tried updating it but nothing happened

**Comment by dbisu** [comment]
Please use putty to get a debug serial trace.

**Comment by dbisu** [comment]
Ensure you are using CircuitPython 8.x and not 9.x.
Closing.
