### ISSUE TITLE
Pico-Ducky not executing script

### ISSUE THREAD

**Issue by stefan2jz** [dbisu/pico-ducky#242]
**Describe the issue**
Ive done this with the help of the tutorials and websites and your webite multiple times . When i get the normal payload it doesnt execute anything . When i plug it in , it opens the file explorer only and doesnt go as a HID. Doesnt execute the script . Idk how to fix.  Im owning a Raspberry Pi Pico

Idk what to change , did everything like in the tutorial . The payload is : 

REM The next four lines open Notepad in Windows and type "Hello World!"
GUI r
STRING notepad
ENTER
DELAY 250
STRING Hello World!

**Screenshots**
These are the screenshots from the Pico 
![1](https://github.com/dbisu/pico-ducky/assets/161526402/988ed19c-018f-4f80-be3c-48330b35b72b)
![2](https://github.com/dbisu/pico-ducky/assets/161526402/de3532dc-5941-4efe-b630-01dc5b996b46)
![3](https://github.com/dbisu/pico-ducky/assets/161526402/35c37be3-e0ab-46aa-ac7a-9e45c9be2b40)

Please help me asap!!

**Comment by oferrr** [comment]
same here

**Comment by dbisu** [comment]
Please submit a debug serial trace of the issue.

**Comment by dbisu** [comment]
Ensure you are using CircuitPython 8.x and not 9.x
Closing.
