### ISSUE TITLE
pico w not executing payload.dd after all steps

### ISSUE THREAD

**Issue by oferrr** [dbisu/pico-ducky#243]
**Describe the issue**
A clear and concise description of the symptoms

**To Reproduce**

**Expected behavior**

**Screenshots**

**Debug info**
If possible, include debug serial data.
On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Additional context**

**Comment by oferrr** [comment]
the device manager pick the pico w as hid device but nothing is happening, only the led starting to flesh.

**Comment by oferrr** [comment]
![image](https://github.com/dbisu/pico-ducky/assets/102322713/1ef95a84-a922-46d5-a15e-d46684f63686)
got that error while executing putty.exe -serial com3

**Comment by oferrr** [comment]
I unplugged the pico completely and i got...the same error? wth

**Comment by oferrr** [comment]
so, i was dumb. i wanst on the correct COM. ops

**Comment by sillymonkey87** [comment]
Im having an issue where i did everything the guide told me to, and my computer detects the pico w as a hid device. but no matter what. it wont run the payload

**Comment by dbisu** [comment]
Are you able to get a debug serial trace of the issue?

**Comment by dbisu** [comment]
Ensure you are using CircuitPython 8.x and not 9.x
Closing.
