### ISSUE TITLE
Pico ducky not working with all steps done

### ISSUE THREAD

**Issue by Miranshkashyap** [dbisu/pico-ducky#246]
After putting payload to pico nothing happens
![17100449114202498291775366905197](https://github.com/dbisu/pico-ducky/assets/162858066/58673ae5-b5fa-4543-9e51-6e2a717db1d3)
Files in pico

![17100449732445466448833428085987](https://github.com/dbisu/pico-ducky/assets/162858066/39b9bc31-5979-4ca1-ab83-be22d9e90b0d)
Files in library

Please help

**Comment by Miranshkashyap** [comment]
Payload
![1710045385484983082226500215483](https://github.com/dbisu/pico-ducky/assets/162858066/965bc8fb-1c07-4b04-9df6-afc345d59041)

**Comment by dbisu** [comment]
I don't see payload.dd in the file list of the first picture.
Have you tried started with the release bundle? You can find the current release [here](https://github.com/dbisu/pico-ducky/releases/tag/v2.0) along with instructions on how to install it.

**Comment by Miranshkashyap** [comment]
Even after adding it, it doesn't works

**Comment by Miranshkashyap** [comment]
It works now thanks
