### ISSUE TITLE
Pico W doesn't work at all

### ISSUE THREAD

**Issue by VyacheslavKuchumov** [dbisu/pico-ducky#248]
ValueError: incompatible .mpy file

code.py output:
Traceback (most recent call last):
  File "code.py", line 14, in <module>
  File "duckyinpython.py", line 9, in <module>
ValueError: incompatible .mpy file

**Comment by dbisu** [comment]
which version of CircuitPython did you program and what library package did you use?
Do you happen to be using CircuitPython 9? and maybe trying to use a 8.x library?

**Comment by VyacheslavKuchumov** [comment]
yeaaaah i accidentally downloaded CircuitPython 9 but it doesn't work with 9.x library either. U should make a link for CircuitPython 8.2.9 in the tutorial
