### ISSUE TITLE
how can i reduce the speed of how fast each character is typed?

### ISSUE THREAD

**Issue by salemnaasan123** [dbisu/pico-ducky#253]
how can i reduce the speed of how fast each character is typed?

**Comment by dbisu** [comment]
probably the easiest way would be to have each character as its own STRING line. If you need more time, you can add DELAY lines between the STRING lines.

**Comment by salemnaasan123** [comment]
Thanks for the feedback, but I am asking because I have like a text of 500 words for exempel that I want to be written, and it will take so long if I just put a delay between each one. My plan is that to make an random delay (from 50 ms to 100 ms) between each charchter. I have tried to modify the code a little but didn't work, I appreciate so much if you give me a solution.

**Comment by salemnaasan123** [comment]
Do you have any idea?

**Comment by salemnaasan123** [comment]
Never mind, Ive edit a bit on the code and now I have a random delay between every character.

**Comment by dbisu** [comment]
ok, sounds good.
Closing, resolved.
