### ISSUE TITLE
Pico payload is not running

### ISSUE THREAD

**Issue by ProtoTypd1** [dbisu/pico-ducky#255]
The Pico is not opening notepad, as expected

Lib folder
![image](https://github.com/dbisu/pico-ducky/assets/167651856/0ea7f34e-c126-47a9-8e35-d3bfa5a4bfa9)
root folder
![image](https://github.com/dbisu/pico-ducky/assets/167651856/e732b141-380f-4192-b8be-9ab0131a5345)
Payload
![image](https://github.com/dbisu/pico-ducky/assets/167651856/52f837b4-6c71-47ba-899b-e7238839f552)

Serial debug using putty
![image](https://github.com/dbisu/pico-ducky/assets/167651856/58afdc3f-8113-435f-92c1-fdb3714d6ac3)

I am using the payload that comes with the install. pls help

**Comment by ProtoTypd1** [comment]
i just used the regular python modules and it worked

**Comment by dbisu** [comment]
This could be caused if you loaded circuitpython 9.x instead of 8.x. I have not yet updated everything to ensure it works with 9.x.

**Comment by ProtoTypd1** [comment]
ok thanks

**Comment by dbisu** [comment]
Closing, resolved.
