### ISSUE TITLE
Can i follow the steps for the regular pico even tho i use pico w?

### ISSUE THREAD

**Issue by ripolofpalme** [dbisu/pico-ducky#261]

**Comment by ripolofpalme** [comment]
Just wondering because when i try to install via the pico w option, the pico doesnt show up in my disks,

**Comment by dbisu** [comment]
By default a Pico W will not show up as a USB drive.
https://github.com/dbisu/pico-ducky?tab=readme-ov-file#usb-enabledisable-mode

**Comment by ripolofpalme** [comment]
Oh okay, but when i put the pi in my pc it doesnt execute the payload

**Comment by ripolofpalme** [comment]
and also since the pico w doesnt show up as a usb drive where do i find the files?

**Comment by arnavgoyal543** [comment]
same
problem with me

**Comment by dbisu** [comment]
Ensure you are using CircuitPython 8.x and not 9.x
Closing.
