### ISSUE TITLE
Payload not running

### ISSUE THREAD

**Issue by aloha9133** [dbisu/pico-ducky#265]
So i tried to make a bad usb but when i plug the pi in my laptop which is windows 11 nothing happenes i followed exact steps and im sure i did nothing wrong although i bought the raspberry pi from aliexpress their are some extra files in it im not sure about i would really apprecieate some help

**Comment by ibrahimxq** [comment]
same here please someone help us

**Comment by aloha9133** [comment]
> same here please someone help us

hi Ibrahim so i figured what the issue is. 
i opened my old very old laptop and it had the old pico ducky files already installed from dbisu and when i tried those files the payloads worked so if u can get the older files your issue will be fixed

**Comment by dbisu** [comment]
It would be helpful in debugging if you had logs from the debug serial port. Are you installing circuitpython 8.x or 9.x? I have not verified 9.x support yet.

**Comment by ibrahimxq** [comment]
yeah, I figured it out and the problem was not reading. hahahaha

**Comment by dbisu** [comment]
Closing, resolved.
