### ISSUE TITLE
HI a problem in your duckyinpython.py file

### ISSUE THREAD

**Issue by ibrahimxq** [dbisu/pico-ducky#267]
HI dbisu,
Without knowing, you put your email address in your duckyinpython.py file. Is this your email: dabailey@gmail.com.
I recommend you take it out and is it yours?

Have a great day.
Ibrahim Qureshi.

**Comment by dbisu** [comment]
I'm not seeing that doing a search in the code. Looks like it is used in the logs, which is not unexpected.
