### ISSUE TITLE
The usb setup mode is not working 

### ISSUE THREAD

**Issue by levitoshiro** [dbisu/pico-ducky#270]
the usb setup mode is not working as it does not prevent the execution of the payload even after i have used jumpers please help me on this one.

**Comment by dbisu** [comment]
Please post the debug serial from your pico. I need more information to help.

**Comment by dbisu** [comment]
Make sure you are jumpers are securely connected to the pins.
Also, ensure you are using circuitpython 8.x and not 9.x
Closing.
