### ISSUE TITLE
Not working normal pico

### ISSUE THREAD

**Issue by sarimwaniR** [dbisu/pico-ducky#271]
FOR THE PICO NOT PICO W
Describe the issue
When I plug in the pico, it doesn't run the payload, instead shows up as a usb. If I push the jumper cable harder and reconnect, nothing shows up, but still decides not to run.
To Reproduce
Use the RPI Pico as normally
Expected behavior
Nothing works as it should

Additional context
Using the default payload after installing in setup mode

(could not understand issue #269 little weak english please help)

**Comment by dbisu** [comment]
For a Pico W, there are two jumper options. One controls if the pico shows up as a usb device, the other controls if the payload runs on boot.
Check both jumpers to makes sure they are in the expected states.
it might be easier to control if you solder the header block to the pins and then use a wire with correct ends to make the jumper.

**Comment by sarimwaniR** [comment]
no I have the normal one

**Comment by sarimwaniR** [comment]
here is the video from start
[](url)https://drive.google.com/file/d/1mXAWOBFQyRVAzJwXiDy58AjDAMp6Xyhg/view?usp=sharing

**Comment by sarimwaniR** [comment]
please  help

**Comment by sarimwaniR** [comment]
#273

**Comment by M1r0zo** [comment]
same problem. it used to work, now just it flashes 3 times, stops, flashes 2 times and then again 2 times in loop
