### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Leapingcactus** [dbisu/pico-ducky#276]
I used all of the files correctly and put them into the correct places, I followed a YouTube tutorial by Austin's lab, and then s tutorial bu network chuck, while following the tutorial by network chuck I deleted some files and cant get them back. Can I please have some help

**Comment by dbisu** [comment]
Your best bet is probably to reset the device with [these](https://github.com/dbisu/pico-ducky/blob/main/RESET.md) instructions and then follow the install instructions [here](https://github.com/dbisu/pico-ducky/releases/tag/v2.0)

**Comment by Leapingcactus** [comment]
Thanks I will let you know if it works, and are there any devices that it
will not work on?

**Comment by dbisu** [comment]
This code has only been tested with RPi Pico and RPI Pico W boards. It might work with other similar boards that run CircuitPython.

**Comment by Leapingcactus** [comment]
Thanks I did it and now it works perfectly, I was using the newest version
of circuit py instead of 8.0.0. Just a question, could I use this code on
picks and sell them?

**Comment by dbisu** [comment]
You can, though keep in mind that the code is released as GPLv2 open-source, so you are really just selling the hardware. The code is released for free.

**Comment by dbisu** [comment]
closing, resolved.
