### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by ibrahimxq** [dbisu/pico-ducky#277]
I am trying to run the pico-ducky, but it runs and then doesn't finish it perfectly, 
GUI r
DELAY 250
STRING cmd
ENTER
DELAY 250
STRING ipconfig
ENTER
 but it only opens the cmd and then doesn't type ipconfig, and it happens to all of the payloads

**Comment by dbisu** [comment]
You may need to add more delay. It is only waiting 1/4 second before doing the ipconfig, which might not be enough time for the cmd window to open.
What happens if you make that second delay 1000 or more?

**Comment by ibrahimxq** [comment]
It works, but I don't know why it opens up Google Chrome and then doesn't work.
Isn't there any way to detect that the app has opened so that it runs the ipconfig?

**Comment by ibrahimxq** [comment]
Now it does work, but by changing this:
WINDOWS r
DELAY 1000
STRING cmd
ENTER
DELAY 1200
STRING ipconfig
ENTER
And it doesn't open Google Chrome.

**Comment by ibrahimxq** [comment]
> It works, but I don't know why it opens up Google Chrome and then doesn't work. Isn't there any way to detect that the app has opened so that it runs the ipconfig, then I will have to reprogram it for the specific computer/laptop.

Please respond to this question first.
And you are also very kind because you help us, not like rude people.😊

**Comment by dbisu** [comment]
There isn't a way for the ducky to know if the command has run successfully. It just acts like a keyboard typing in characters.

**Comment by ibrahimxq** [comment]
Oh, ok but then how should I program my rubber ducky? Should I program it to go slow or fast? Because I have another computer that is slow and in that, I need to put a slower delay In that computer.

**Comment by dbisu** [comment]
That is the trick with the payloads. sometimes the best thing is to run and time the steps manually to get an idea on how long each step takes. If the goal is to automate some things, it might not matter that it takes as long with the ducky as it does manually.

**Comment by nebuleex** [comment]
is it 250ths of a second for the delay?

**Comment by dbisu** [comment]
Delay is in milliseconds.

**Comment by dbisu** [comment]
closing, answered.
