### ISSUE TITLE
Scripts are not running, only opens pico file directory on target device

### ISSUE THREAD

**Issue by Spathy01** [dbisu/pico-ducky#278]
I did all the steps but the payload.dd doesnt run when i plug in the pico. here are some screensthots of my files for my pico and payload: 
![image](https://github.com/user-attachments/assets/31cfe36f-b081-4052-bd64-36ecd3adad8a)
![image](https://github.com/user-attachments/assets/f3740e99-b216-4fcf-b828-07b1773e4b64)

I have tried unplugging the pico and plugging it back into the host pc but still doesnt work. It only opens the picos file system as if it were a normal usb storage drive. 

Is there any way to fix this?

**Comment by Spathy01** [comment]
i have realised that maybe its because it isnt being registered as a HID device but as a disk, could this be the issue even though i have all the neccessary files in my pico lib directory? if this is the issue how would i fix it.
![image](https://github.com/user-attachments/assets/3206d9cc-ef19-4799-9408-1bbc7f4cc044)

**Comment by dbisu** [comment]
Make sure you are using CircuitPython 8.x and not 9.x. The project hasn't been updated yet to support 9.x.

**Comment by Spathy01** [comment]
> Make sure you are using CircuitPython 8.x and not 9.x. The project hasn't been updated yet to support 9.x.

I am using circuit python 8x but it still doesn't work?

**Comment by dbisu** [comment]
Have you tried using one of the release bundles found [here](https://github.com/dbisu/pico-ducky/releases)?

**Comment by Spathy01** [comment]
I solved the issue, must've been a problem on my part thanks tho.

**Comment by dbisu** [comment]
Closing, resolved.
