### ISSUE TITLE
Problem with USB enable/disable mode

### ISSUE THREAD

**Issue by TheMrM** [dbisu/pico-ducky#292]
For the Pico pi w model.
When I place jumpers on pin 18 (GND) and pin 20 (GPIO15), and plug it into my PC, the files are shown but the script also runs, which it should not.
These are all my files when the Py is running as CIRCUITPY
![image](https://github.com/user-attachments/assets/dd8ff4d8-e6f8-4955-967b-3809e8f6705a)

I don't know if this is the correct place to make an issue regarding the problem.
Also, this is the guide that I followed https://www.youtube.com/watch?v=ctCmOhoT9po

**Comment by dbisu** [comment]
On a Pico W, you need the jumper wire to make it show up as a USB drive. Without the jumper it will not show up as a USB drive.
This sounds like it is running as designed.

**Comment by TheMrM** [comment]
I am using the jump wires so I can see it as usb, but my problem is, it also runs the script.

**Comment by dbisu** [comment]
Correct, you need to put a jumper from pin 1 to pin 3 to enter setup mode. In setup mode it will not auto run the scripts.

**Comment by TheMrM** [comment]
I also did that, but then I don't have access to the files

**Comment by TheMrM** [comment]
Wait you mean I need jumpers on both 1 and 3 , 18 and 20 , at the same time?

**Comment by dbisu** [comment]
Yes, both at the same time. they are separate functions.

**Comment by TheMrM** [comment]
OMG, I have not thought of that. Thank you very much! Will give it a go. And thanks for the time you took to help me out with the issue!

**Comment by TheMrM** [comment]
Thank you very much! I just tried it out and it worked. Gonna close this issue now.
