### ISSUE TITLE
ducky isnt workuing in rpi pico 1

### ISSUE THREAD

**Issue by Linkinmyyt** [dbisu/pico-ducky#298]
i held BOOTSEL when pluging it in but still nothing, i dont think i did anything wrong, i mean when i copied it over i didnt select them all at once, in the instructions there were 4 things to install in one step, idk if it helps but im using this micro usb cable
![eardom](https://github.com/user-attachments/assets/df504449-f732-4844-92f7-a7d759e08bce)
![Screenshot 2024-12-19 204012](https://github.com/user-attachments/assets/976b073e-90b1-4ec9-a044-97b225adfd87)
![Screenshot 2024-12-19 204051](https://github.com/user-attachments/assets/4cc5f543-1ed0-41e7-b765-31a9f2ed54f7)

**Comment by dbisu** [comment]
What version of CircuitPython did you install? I'm working on adding support for 9.x soon.

**Comment by dbisu** [comment]
Try updating to the v3.0 release to see if that fixes your problem.

**Comment by Linkinmyyt** [comment]
can you give me a link bc im not finding it

**Comment by dbisu** [comment]
You can find the release bundles [here](https://github.com/dbisu/pico-ducky/releases/tag/v3.0)

**Comment by Linkinmyyt** [comment]
still not working, i did everything in the instructions besides setup mode and i downloaded the right uf2 file too.

**Comment by Linkinmyyt** [comment]
i know the cable isn't the one at fault bc i could upload stuff with it.

**Comment by Linkinmyyt** [comment]
it registers as a hid device bc when i unplug it these two disappear
![Screenshot 2024-12-22 200741](https://github.com/user-attachments/assets/ea5befe8-b68f-46cb-bfc4-56374d491ff1)

**Comment by dbisu** [comment]
Follow the instructions [here](https://github.com/dbisu/pico-ducky/blob/main/DEBUG.md) to collect more debug data.

**Comment by Linkinmyyt** [comment]
It was COM5 for me but what do i do now
![Screenshot 2024-12-23 205839](https://github.com/user-attachments/assets/b15855e6-4786-4efd-a9b4-6abb0a5d030f)

**Comment by Linkinmyyt** [comment]
It was COM5, but i got this screen so i left it for half an hour and it was still the same
![Screenshot 2024-12-23 205839](https://github.com/user-attachments/assets/624f05f4-1c18-48d5-a963-39000b3dfe21)

**Comment by dbisu** [comment]
In the putty window, hit Ctl+C, then Ctl+D and then send the debug output.

**Comment by Linkinmyyt** [comment]
heres the output
![Screenshot 2024-12-23 223048](https://github.com/user-attachments/assets/949a983c-2129-4e3d-94b3-44c09e72a1d7)

**Comment by dbisu** [comment]
Looks like the file payload.dd is missing or unreadable. double check that file is there and has text contents.

**Comment by Linkinmyyt** [comment]
IT WORKED! i just had to make it with notepad++, thanks for the help
