### ISSUE TITLE
After copying the UF2, the pico appears as a 1MB volume instead of CIRCUITPYTHON

### ISSUE THREAD

**Issue by SemiConductorShortage** [dbisu/pico-ducky#37]
![image](https://user-images.githubusercontent.com/83015532/142985154-c17d0c07-8bfc-4803-a39e-6fa0670dc4c4.png)
when i try to open the volume created, this shows up^

**Comment by SemiConductorShortage** [comment]
resolved; i had to use the nuke.uf2 and reflash circuitpython

**Comment by dbisu** [comment]
Closing, problem resolved.
