### ISSUE TITLE
Don't run the script always after plugging the Pico

### ISSUE THREAD

**Issue by Maxisy** [dbisu/pico-ducky#44]
Hi, thanks for the project! Is there any way to connect e.g. a button to Pico and when it's clicked the script isn't executed after plugging it to a PC and vice versa? It would make the script change process so much easier.

**Comment by dbisu** [comment]
Check out programming mode.  That prevents the script from running when plugged into a PC.
I have a prototype on my bench that uses slides switches and am in the process of creating a real PCB that will include switches for programming plus some other features.

**Comment by dbisu** [comment]
Closing, this feature already exists.
