### ISSUE TITLE
Can it hide the window when i plug it in?

### ISSUE THREAD

**Issue by Sifuniaris** [dbisu/pico-ducky#47]
Hello, i was wondering if the pico is able to hide the window when i plug it in a computer. And ny window i mean like the one when you plug a regular usb.

**Comment by peterfritz** [comment]
Just add WIN + D at the start of the script. I do not recommend sending ALT + F4 as not all PCs automatically open the device when plugged in.

**Comment by dbisu** [comment]
If you don't need the mass storage capability within the script (which most don't), you can disable mass storage mode by connecting pins 18 and 20.
See https://github.com/dbisu/pico-ducky#usb-enabledisable-mode
This will prevent the USB drive window from popping up on the target PC.

**Comment by Sifuniaris** [comment]
Thanks a lot!!
