### ISSUE TITLE
Can't find the Scandinavian LANG

### ISSUE THREAD

**Issue by booscloos** [dbisu/pico-ducky#48]
My country is Sweden and I've been trying to change the LANG in code.py to "swe","sw","SWE","SE" and alot more, please if anyone knows the name for LANG for Swedish then it would be appreciated

**Comment by VibeVike** [comment]
mind sharing the new code?

**Comment by VibeVike** [comment]
Mind giving the code?

**Comment by dbisu** [comment]
You will need to follow the instructions [here](https://github.com/dbisu/pico-ducky#changing-keyboard-layouts) and use the link above to get the correct keyboard layout.
