### ISSUE TITLE
Twin duck

### ISSUE THREAD

**Issue by Falabdullateef** [dbisu/pico-ducky#54]
When a file enters the pico it runs the payload again I need it like a rubber ducky twinduck.@dbisu

**Comment by dbisu** [comment]
This looks possible by adding a call to supervisor.disable_autoreload()
I'll mark this issue as a feature request.  I should be able to get this added in the next couple of weeks.

**Comment by Falabdullateef** [comment]
Alright thank you for the fast reply and hopefully fast fix
Please I need this in the next couple of days not weeks.
Thank you

**Comment by dbisu** [comment]
Feel free to submit a PR with a proposed change.  I work on this project in my free time and I have some other projects that need my attention first.
