### ISSUE TITLE
FR: select program

### ISSUE THREAD

**Issue by mm12** [dbisu/pico-ducky#62]
Use pins to allow selection of a different payload.

**Comment by dbisu** [comment]
This request has already been implemented.
# payload1 = GPIO4 to GND
# payload2 = GPIO5 to GND
# payload3 = GPIO10 to GND
# payload4 = GPIO11 to GND

**Comment by mm12** [comment]
Although, it might be better if you selected with multiple switches using binary, then you could have 16 total programs
