### ISSUE TITLE
Multi Key Support

### ISSUE THREAD

**Issue by eastoncrafter** [dbisu/pico-ducky#64]
It does not seem like this project has support for multiple keys pressed at a time. You can do this on the classic rubber ducky by using CTRL-ALT and CTRL-SHIFT. This allows CTRL-ATL DEL, and CTRL-SHIFT Enter.

**Comment by dbisu** [comment]
This is supported.  You need to separate each key by a space, so CTRL ALT. 
The demo payload (payload.dd) in the project shows GUI r to get to the Windows Run menu.

**Comment by eastoncrafter** [comment]
I see now, I had to put a delay because my computer was not fast enough. Thanks!
