### ISSUE TITLE
Error changing the LANG to spanish

### ISSUE THREAD

**Issue by wachopistacho** [dbisu/pico-ducky#71]
Hi! Im from Spain and Im having problems when i try to change the US keyboard to the spanish keyboard. Im uncomment the lines and commenting the US lines, but it didnt work. I would appreciate these lines because I dont understand python. Thx!

**Comment by dbisu** [comment]
Check out the releases section.  There is a release bundle for Spanish (ES) keyboards.
https://github.com/dbisu/pico-ducky/releases/download/v1.3/pico-ducky-v1.3_win_es.zip

**Comment by dbisu** [comment]
Closing, no update.

**Comment by IIT0** [comment]
Hii, I don't understand how to change to spanish I need some help pls
