### ISSUE TITLE
Unable to select payloads

### ISSUE THREAD

**Issue by Jakubikk** [dbisu/pico-ducky#74]
Whenever I ground GPIO4/5/10/11 always payload.dd is executed, no matter the grounded pin.

**To Reproduce**

1.Upload 4 files named named payload.dd, payload2.dd, payload3.dd and payload4.dd (each one opens the Mac Spotlight and types its script's number)(included in the zip)
[ducky scripts.zip](https://github.com/dbisu/pico-ducky/files/8750128/ducky.scripts.zip)

2.Ground pin GPIO 5, 10 or 11 (GPIO 10 is grounded in the picture)
![IMG_4195](https://user-images.githubusercontent.com/83714079/169712529-eae697a6-1b87-4ee7-8260-ceb408aebe83.jpg)

3.Reboot board

4.Spotlight opens, 1 is typed (result visible in screenshot)

**Expected behavior**

Script runs, spotlight opens and "3" is typed (as pin GPIO 10 is grounded in the example)

**Screenshots**

<img width="673" alt="Screenshot 2022-05-22 at 21 24 11" src="https://user-images.githubusercontent.com/83714079/169712430-78c6b2f0-cf81-4bea-a8c2-0ae748a4ec20.png">

**Debug info**
Wasn't able to to obtain any :(
**Additional context**

I am using a Mac, that's why I use spotlight, which is summoned with GUI TAB

**Comment by dbisu** [comment]
Here is a picture of the schematic I've used to implement the switching behavior.
```
Payload 1 = Pin 6 (GPIO4) to Pin 8 (GND)
Payload 2 = Pin 7 (GPIO5) to Pin 13 (GND)
Payload 3 = Pin 14 (GPIO10) to Pin 8 (GND)
Payload 4 = Pin 15(GPIO11) to Pin 13 (GND)
```
![image](https://user-images.githubusercontent.com/11895624/169714508-b6c7f5a3-d656-41c9-afcd-2a81e7ac0d8b.png)

**Comment by Jakubikk** [comment]
That seems to work perfectly, thanks!
