### ISSUE TITLE
Payload wont run even when everything has been done correctly

### ISSUE THREAD

**Issue by Jimby1234** [dbisu/pico-ducky#79]
![image](https://user-images.githubusercontent.com/108219349/175810342-155efd47-6e7e-4cf8-a9fb-606fb1f30a37.png)
the image above is what my pico looks like inside. I dont really know the problem so theres nothing really for me to say but what i can say is its not working

**Comment by dbisu** [comment]
**Debug info**
 If possible, include debug serial data. On Windows, use PuTTY, connect to the debug serial port (commonly COM3, but could vary)

On Linux, use minicom (minicom -b 115200 -o -D /dev/ttyACM0, where ttyACM0 corresponds to your device)

**Comment by MonsieurPoutounours** [comment]
In your picture, the .metadata_never_index file does not have extension shown. So your OS may have "Don't show file extension for known filetypes" checked. 

You payload.dd may indeed be a payload.dd.txt file, which is something that Windows Notepad tend to do if you're not careful (stop using Windows Notepad, use a real file editor). 

Check that.

**Comment by p-i-c-o** [comment]
Hi, I have the same issue, Im not sure what i need to look for in general. all files are ok, but payload.dd doesn't run
<img width="764" alt="Screen Shot 2022-08-30 at 19 05 00" src="https://user-images.githubusercontent.com/95228665/187497261-796200e8-571a-43ff-8dfd-242edb8541fe.png">

**Comment by dbisu** [comment]
To have a better idea why it isn't working, I need a dump from the debug serial.
On Linux:
minicom -b 115200 -o -D /dev/ttyACM0

**Comment by p-i-c-o** [comment]
How do you do this on MacOS?

**Comment by dbisu** [comment]
It looks like you can use screen from a macos terminal
screen /dev/<serial port> 115200
You may need to watch /dev to see what port appears when you plug in the pico.

**Comment by p-i-c-o** [comment]
Hey everyone, I'm back,
using Mu Code Editor ( which supports MicroPython ), i found this in the Serial:

<img width="805" alt="Screen Shot 2022-09-02 at 13 48 37" src="https://user-images.githubusercontent.com/95228665/188134220-1cddee0b-b756-4281-8913-1534969bf135.png">

**Comment by p-i-c-o** [comment]
Could someone provide code from a working Pico Ducky so that I could compare?

Thanks

**Comment by dbisu** [comment]
Main is currently broken.  I have a PR open to fix it and I'll get it merged in tonight or tomorrow.
You could grab the current release [here](https://github.com/dbisu/pico-ducky/releases/tag/v1.3)

**Comment by dbisu** [comment]
Main should be fixed now.

**Comment by N-00-B** [comment]
![COM4-PuTTY](https://user-images.githubusercontent.com/112816303/188321375-b89f6536-f4f6-4214-893d-7669b728ce3b.png)

Hi all, I'm relatively new to this stuff so bear with me.. 

I had similar issues with my Pi so I waited until the main was fixed. However, when I followed all steps correctly, even attempting it multiple times, my payloads were not executing. So I downloaded PuTTY and got the debug serial data and this traceback message..

**Comment by dbisu** [comment]
Based on the errors, it is likely you missed the update to the README.md instructions that included this line:
Copy adafruit_debouncer.mpy and adafruit_ticks.mpy to the lib folder in your Raspberry Pi Pico.

Copy those two files from the adafruit library bundle (same place that adafruit_hid is in) to the lib folder on the pico.

**Comment by N-00-B** [comment]
Oh wow, I did not take note of that at first XD.. Thank you!

**Comment by dbisu** [comment]
Closing, main should be working now.
