### ISSUE TITLE
Is there any way to use the Fn key?

### ISSUE THREAD

**Issue by Apolycious** [dbisu/pico-ducky#81]
So I was trying the Function key (F11) in my payload script but when I run it, it presses the Fn key and F11 simultaneously without being included in the script.

**Comment by dbisu** [comment]
I don't believe there are standard keycodes for the Fn key.  I didn't see it in the USB HID spec.
https://usb.org/sites/default/files/hut1_21_0.pdf#page=83

**Comment by Apolycious** [comment]
So is there any ways that the script will just run the function command without the fn key?

**Comment by dbisu** [comment]
which function are you trying to send?  there may be other ways of accomplishing the same goals.

**Comment by Apolycious** [comment]
I'm using the F11 functions to screenshot the desktop
