### ISSUE TITLE
disable usb drive

### ISSUE THREAD

**Issue by BlackDemonHat** [dbisu/pico-ducky#84]
how i can put a counter that enable usb drive at 20 secons i made i and i put in code.py but did't work

![image](https://user-images.githubusercontent.com/105757180/180648049-fab6c3f3-9858-4229-8edb-22cae1817fdf.png)

**Comment by dbisu** [comment]
Unfortunately, the way the storage module works in CircuitPython, you can only change the USB state in boot.py and not in code.py.

**Comment by ratarchivos** [comment]
> Unfortunately, the way the storage module works in CircuitPython, you can only change the USB state in boot.py and not in code.py.

with a import boot.py or from boot.py import usbDrive
meaby i can put that counter and when finish change the boot.py to false

**Comment by dbisu** [comment]
boot.py is only executed on cold boot, so changing this file will only take effect the next time the device is power cycled.

**Comment by dbisu** [comment]
Closing this issue, not possible to change USB status in CircuitPython in code.py, only boot.py.
