### ISSUE TITLE
i can put the ducky in micropython?

### ISSUE THREAD

**Issue by pythondemon** [dbisu/pico-ducky#87]

**Comment by ratarchivos** [comment]
because micro have support for pico w

**Comment by dbisu** [comment]
I haven't tried porting to micropython.  I think it should mostly work.  there might be a few things that are circuitpython specific. Non-US keyboard support might be the biggest challenge.

**Comment by dbisu** [comment]
Closing.  this repo is focused on CircuitPython based Pico and Pico W.
