### ISSUE TITLE
Run on thumby?

### ISSUE THREAD

**Issue by slothstronomic** [dbisu/pico-ducky#88]
I want to run this on a miniature game console called the [Thumby](https://thumby.us), which runs on the RP2040 microchip. Would it work?

**Comment by dbisu** [comment]
I think it might work if you can get circuitpython running on this board.  Micropython could be an option also if non-US keyboards are not an immediate concern.

**Comment by dbisu** [comment]
Closing, this repo is focused on Pico and Pico W.
The code base should be portable to other boards that support circuitpython.
