### ISSUE TITLE
Button to deploy Payload

### ISSUE THREAD

**Issue by k-pr1m3** [dbisu/pico-ducky#91]
Any instructions on how to add a button to the pico to deploy your payload?

**Comment by dbisu** [comment]
I can probably code something up this weekend.  I've got examples from other projects.

**Comment by k-pr1m3** [comment]
That could be awesome.... Have a nice day  :)

**Comment by dbisu** [comment]
Added the option for a button on GPIO22.
Created PR #92 for this issue.  I'll merge it tomorrow.
