### ISSUE TITLE
Assets on Root directory

### ISSUE THREAD

**Issue by LyQuid12** [dbisu/pico-ducky#94]
Is it possible to put assets on Pico's root directory? So when run on a computer, it doesn't need to download the assets, just copy from root directory.

**Comment by LyQuid12** [comment]
Nvm, it works

**Comment by d3k4-k3rb3r0s** [comment]
err, elaborate? that sounds like a game changer..

**Comment by dbisu** [comment]
It is possible to store some files locally on the USB mass storage part of the Pico.  There is, I believe, less than 1MB of storage available, so your assets need to be fairly small.
You need to have a good idea on where it will mount/enumerate on your target computer for the scripts to work properly.

**Comment by d3k4-k3rb3r0s** [comment]
interesting. the least appealing thing about ducks is that we almost always have to rely on having the target reach out and pull down the true payload.

**Comment by LyQuid12** [comment]
> It is possible to store some files locally on the USB mass storage part of the Pico. There is, I believe, less than 1MB of storage available, so your assets need to be fairly small. You need to have a good idea on where it will mount/enumerate on your target computer for the scripts to work properly.

Yea, i have to compress my bmp file which was originally 9 mb to 200kb :|
