### ISSUE TITLE
Twin Ducky

### ISSUE THREAD

**Issue by armendvin** [dbisu/pico-ducky#97]
Is it possible to add twin ducky

**Comment by dbisu** [comment]
My understanding of twin ducky is that is mounts like a USB drive and then deploys the payload on a button push.  This is already there.  I'm merging in a PR that improves the button handling.

**Comment by dbisu** [comment]
Closing, feature added.

**Comment by armendvin** [comment]
How do I implement this into the pico

**Comment by armendvin** [comment]
How do I implement this into the pico
